import Foundation
import GRDB
import Testing
@testable import InterviewCopilotMac

@Suite(.serialized)
@MainActor
struct GenerationContextIsolationTests {
    @Test
    func promptStartsWithExactCurrentQuestionAndLabelsBackground() {
        let current = makeQuestion("Why did the diffusion-based policy perform better than the autoregressive policy?")
        let snapshot = AnswerRelevancePolicy.promptSnapshot(
            question: current,
            context: mixedContext(),
            transcriptContext: "Interviewer: Which part of the LeoRover pipeline was most fragile when moving from a clean demo to real robot execution?",
            cvSummary: "Candidate has robotics, LeoRover, and VLA experience.",
            jdSummary: "Robotics role.",
            stage: .firstAnswer
        )

        #expect(snapshot.prompt.hasPrefix("""
        CURRENT QUESTION TO ANSWER:
        "\(current.questionText)"
        """))
        let questionRange = snapshot.prompt.range(of: "CURRENT QUESTION TO ANSWER:")
        let backgroundRange = snapshot.prompt.range(of: "BACKGROUND FROM EARLIER INTERVIEW")
        #expect(questionRange != nil)
        #expect(backgroundRange != nil)
        if let questionRange, let backgroundRange {
            #expect(questionRange.lowerBound < backgroundRange.lowerBound)
        }
        #expect(snapshot.prompt.localizedCaseInsensitiveContains("Previous transcript is background only and must not change the question."))
        #expect(snapshot.prompt.localizedCaseInsensitiveContains("Which part of the LeoRover pipeline was most fragile") == false)
    }

    @Test
    func firstAnswerWorthyQuestionIsNotSuppressedByStaleDuplicateMemory() async throws {
        let client = ContextIsolationLLMClient()
        let (appState, _, session) = try makeAppState(client: client)
        let questionText = "First, could you tell me a little bit about yourself and what brought you into robotics?"

        #expect(appState.isDuplicateAutoQuestion(questionText) == false)

        await appState.handleTranscriptSegment(systemAudioSegment(
            id: "first-stale-duplicate-segment",
            sessionID: session.id,
            text: questionText
        ))

        try await waitUntil(timeout: 8.0) {
            appState.detectedQuestionsInSessionCount == 1 &&
            appState.lastTranscriptQuestionGenerationTrace.generationTriggered &&
            appState.visibleAnswerExists
        }

        #expect(appState.lastTranscriptQuestionGenerationTrace.duplicateSuppressed == false)
        #expect(appState.currentSuggestion?.detectedQuestionID == appState.lastDetectedQuestion?.id)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
    }

    @Test
    func fragilityThenDiffusionQuestionUsesCurrentSnapshotAndIntentContext() async throws {
        let client = ContextIsolationLLMClient()
        let retrieval = ContextIsolationRetrievalService()
        let (appState, _, session) = try makeAppState(client: client, retrievalService: retrieval)
        let first = try saveQuestion(
            "Which part of the pipeline was most fragile when moving from a clean demo to real robot execution?",
            sessionID: session.id,
            repository: appState.suggestionRepository,
            suffix: "fragility"
        )
        let second = try saveQuestion(
            "Why did the diffusion-based policy perform better than the autoregressive policy?",
            sessionID: session.id,
            repository: appState.suggestionRepository,
            suffix: "diffusion"
        )

        let firstTask = Task {
            try await appState.generateSuggestion(for: first, session: session, transcript: first.questionText, autoGenerated: true)
        }
        try await waitUntil(timeout: 8.0) {
            appState.currentSuggestion?.detectedQuestionID == first.id || appState.activeQuestionID == first.id
        }

        let secondTask = Task {
            try await appState.generateSuggestion(
                for: second,
                session: session,
                transcript: "Interviewer: \(first.questionText)\nInterviewer: \(second.questionText)",
                autoGenerated: true
            )
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.currentSuggestion?.detectedQuestionID == second.id &&
            appState.currentQABinding.bindingStatus == .matched
        }

        let card = try #require(appState.currentSuggestion)
        #expect(card.questionText == second.questionText)
        #expect(card.promptQuestionText == second.questionText)
        #expect(card.sayFirst.localizedCaseInsensitiveContains("diffusion"))
        #expect(card.sayFirst.localizedCaseInsensitiveContains("autoregressive"))
        #expect(card.sayFirst.localizedCaseInsensitiveContains("smoother"))
        #expect(card.sayFirst.localizedCaseInsensitiveContains("robust"))
        #expect(card.sayFirst.localizedCaseInsensitiveContains("pipeline was most fragile") == false)
        #expect(appState.currentPromptContextPreviews.joined(separator: " ").localizedCaseInsensitiveContains("diffusion"))
        #expect(appState.currentPromptContextPreviews.joined(separator: " ").localizedCaseInsensitiveContains("pipeline was most fragile") == false)
        #expect(client.stageAPrompts.last?.hasPrefix("CURRENT QUESTION TO ANSWER:") == true)
        #expect(retrieval.queries.suffix(2).map(\.question) == [first.questionText, second.questionText])
    }

    @Test
    func promptSnapshotFrozenEvenIfLatestQuestionMutatesDuringGeneration() async throws {
        let client = ContextIsolationLLMClient()
        client.stageADelayNanoseconds = 250_000_000
        let (appState, _, session) = try makeAppState(client: client)
        let frozen = try saveQuestion(
            "Why did the diffusion-based policy perform better than the autoregressive policy?",
            sessionID: session.id,
            repository: appState.suggestionRepository,
            suffix: "frozen"
        )
        let later = try saveQuestion(
            "Why do you want to join our team?",
            sessionID: session.id,
            repository: appState.suggestionRepository,
            suffix: "later"
        )

        let task = Task {
            try await appState.generateSuggestion(for: frozen, session: session, transcript: frozen.questionText, autoGenerated: true)
        }
        defer { task.cancel() }
        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == frozen.id
        }

        appState.lastDetectedQuestion = later
        appState.lastDetectedQuestionText = later.questionText

        try await waitUntil(timeout: 8.0) {
            appState.currentSuggestion?.detectedQuestionID == frozen.id
        }

        #expect(client.stageAPrompts.last?.localizedCaseInsensitiveContains(frozen.questionText) == true)
        #expect(client.stageAPrompts.last?.localizedCaseInsensitiveContains(later.questionText) == false)
        #expect(appState.currentSuggestion?.questionText == frozen.questionText)
    }

    @Test
    func alignmentEvaluatorRecognizesDiffusionPolicyQuestion() {
        let result = QuestionAnswerAlignmentEvaluator.evaluate(
            questionText: "Why did the diffusion-based policy perform better than the autoregressive policy?",
            answerText: "The diffusion policy performed better because it generated smoother continuous actions, handled the action distribution more robustly than the autoregressive and flow-matching variants, and reached seven out of ten successful grasps."
        )

        #expect(result.verdict == .aligned)
        #expect(result.questionIntent == .modelComparison)
    }

    @Test
    func databasePersistsPromptPrimaryQuestionForRuntimeAlignmentQuery() throws {
        let database = try TestSupport.makeTemporaryDatabase(prefix: "GenerationContextIsolationDB")
        let sessions = SessionRepository(database: database)
        let repository = SuggestionRepository(database: database)
        let session = try sessions.createSession(mode: .mock, title: "Context DB")
        let sessionID = session.id
        let question = makeQuestion(
            "Why did the diffusion-based policy perform better than the autoregressive policy?",
            sessionID: sessionID,
            suffix: "db"
        )
        try repository.saveDetectedQuestion(question)
        var card = SuggestionCard(
            id: "context-db-card",
            sessionID: sessionID,
            questionID: question.id,
            strategy: "Current question answer",
            sayFirst: "The diffusion policy performed better because it produced smoother continuous actions and was more robust than the autoregressive policy.",
            keyPoints: ["Diffusion smoother", "Autoregressive less robust"],
            followUpReady: [],
            confidence: 0.9,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .low,
            modelName: "test",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )
        card.questionText = question.questionText
        card.promptQuestionText = question.questionText
        card.promptPrimaryQuestion = question.questionText
        card.questionIntent = .modelComparison
        card.alignmentVerdict = .aligned

        try repository.saveSuggestionCard(card)

        let row = try database.dbQueue.read { db in
            try Row.fetchOne(
                db,
                sql: """
                SELECT
                  substr(question_text,1,160) AS question,
                  question_intent,
                  substr(prompt_primary_question,1,160) AS prompt_question,
                  alignment_verdict
                FROM suggestion_cards
                WHERE id = ?
                """,
                arguments: [card.id]
            )
        }
        #expect(row?["question"] as String? == question.questionText)
        #expect(row?["prompt_question"] as String? == question.questionText)
        #expect(row?["question_intent"] as String? == AnswerRelevanceIntent.modelComparison.rawValue)
        #expect(row?["alignment_verdict"] as String? == AnswerAlignmentVerdict.aligned.rawValue)
    }

    private func makeAppState(
        client: ContextIsolationLLMClient,
        retrievalService: ContextIsolationRetrievalService = ContextIsolationRetrievalService()
    ) throws -> (AppState, AppDatabase, InterviewSession) {
        let database = try TestSupport.makeTemporaryDatabase(prefix: "GenerationContextIsolation")
        let settingsRepository = SettingsRepository(database: database)
        try settingsRepository.ensureDefaultProviderConfigurations()
        if let deepSeek = try settingsRepository.providerConfigurations().first(where: { $0.kind == .deepSeek }) {
            try settingsRepository.setActiveRealtimeProvider(id: deepSeek.id)
        }

        let router = LLMRouter(settingsRepository: settingsRepository, clients: [.deepSeek: client])
        let appState = AppState(database: database, llmRouter: router, contextRetrievalService: retrievalService)
        appState.detectionDebounceSeconds = 0.01
        appState.delayProvider = MockDelayProvider()
        appState.generationFullCardWatchdogNanoseconds = 1_000_000_000
        var settings = appState.settings
        settings.audioCaptureMode = .systemAudioOnly
        settings.automaticQuestionDetectionEnabled = true
        settings.allowQuestionDetectionFromMicrophoneOnly = false
        settings.saveTranscriptsLocally = true
        appState.saveSettings(settings)

        let session = try appState.sessionRepository.createSession(mode: .microphone)
        appState.currentSession = session
        appState.liveState = .listening
        appState.currentCaptureRuntimeState = .listening
        return (appState, database, session)
    }

    private func saveQuestion(
        _ text: String,
        sessionID: String,
        repository: SuggestionRepository,
        suffix: String
    ) throws -> DetectedQuestion {
        let question = makeQuestion(text, sessionID: sessionID, suffix: suffix)
        try repository.saveDetectedQuestion(question)
        return question
    }

    private func makeQuestion(_ text: String, sessionID: String = "generation-context-session", suffix: String = UUID().uuidString) -> DetectedQuestion {
        DetectedQuestion(
            id: "context-\(suffix)-\(UUID().uuidString)",
            sessionID: sessionID,
            transcriptSegmentID: nil,
            questionText: text,
            intent: .technical,
            answerStrategy: .technicalExplanation,
            confidence: 0.95,
            reason: "Context isolation fixture",
            shouldTrigger: true,
            questionComplete: true,
            modelName: "test",
            promptVersion: "test",
            createdAt: Date()
        )
    }

    private func systemAudioSegment(id: String, sessionID: String, text: String) -> TranscriptSegment {
        TranscriptSegment(
            id: id,
            sessionID: sessionID,
            source: .systemAudio,
            speaker: .interviewer,
            text: text,
            createdAt: Date(),
            confidence: 1.0
        )
    }

    private func waitUntil(timeout: TimeInterval, predicate: @escaping @MainActor () -> Bool) async throws {
        let start = Date()
        while !predicate() {
            if Date().timeIntervalSince(start) > timeout {
                throw NSError(
                    domain: "GenerationContextIsolationTests",
                    code: 1,
                    userInfo: [NSLocalizedDescriptionKey: "Timed out waiting for generation context isolation state."]
                )
            }
            try await Task.sleep(nanoseconds: 25_000_000)
        }
    }

    private func mixedContext() -> RetrievedContext {
        ContextIsolationRetrievalService.context
    }
}

private final class ContextIsolationLLMClient: LLMClientProtocol, @unchecked Sendable {
    let providerKind: LLMProviderKind = .deepSeek
    var stageADelayNanoseconds: UInt64 = 0
    private let lock = NSLock()
    private var recordedStageAPrompts: [String] = []

    var stageAPrompts: [String] {
        lock.withLock { recordedStageAPrompts }
    }

    func testConnection(configuration: LLMProviderConfiguration) async throws -> LLMConnectionTestResult {
        LLMConnectionTestResult(success: true, message: "Mock OK", latencyMS: 0, models: [])
    }

    func chatCompletion(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) async throws -> LLMChatResult {
        let prompt = messages.map(\.content).joined(separator: "\n")
        if prompt.contains("Decide whether the interviewer has asked") {
            return detectionResult(for: prompt)
        }
        let question = currentQuestion(from: prompt)
        let content = """
        {
          "strategy": "Current question answer",
          "say_first": "\(Self.jsonEscaped(sayFirst(for: question)))",
          "key_points": ["\(Self.jsonEscaped(keyPoint(for: question)))", "Current-question specific"],
          "follow_up_ready": ["I can go deeper if useful."],
          "confidence": 0.88,
          "caution": "None",
          "evidence_used": [],
          "risk_level": "low"
        }
        """
        return LLMChatResult(content: content, modelName: "context-isolation-mock", providerKind: .deepSeek, providerName: "DeepSeek", baseURL: "", latencyMS: 10, isLocal: false, rawResponse: content)
    }

    func chatCompletionStream(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) -> AsyncThrowingStream<String, Error> {
        let prompt = messages.map(\.content).joined(separator: "\n")
        let userPrompt = messages.last?.content ?? prompt
        let isStageB = prompt.contains("Return plain text sections only")
        let question = currentQuestion(from: userPrompt)
        if !isStageB {
            lock.withLock { recordedStageAPrompts.append(userPrompt) }
        }
        let delay = stageADelayNanoseconds
        return AsyncThrowingStream { continuation in
            let task = Task {
                if !isStageB, delay > 0 {
                    try? await Task.sleep(nanoseconds: delay)
                }
                if isStageB {
                    for token in sectionAnswer(for: question) {
                        if Task.isCancelled { break }
                        continuation.yield(token)
                    }
                } else {
                    for token in sayFirst(for: question).split(separator: " ", omittingEmptySubsequences: false) {
                        if Task.isCancelled { break }
                        continuation.yield(String(token) + " ")
                    }
                }
                continuation.finish()
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    func listModels(configuration: LLMProviderConfiguration) async throws -> [LLMModelInfo] {
        []
    }

    private func detectionResult(for prompt: String) -> LLMChatResult {
        let line = prompt
            .components(separatedBy: "Recent transcript:")
            .last?
            .components(separatedBy: "Decide whether")
            .first ?? prompt
        let question = line
            .replacingOccurrences(of: "Interviewer:", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let content = """
        {
          "should_trigger": true,
          "question_complete": true,
          "question_text": \(Self.jsonString(question)),
          "intent": "technical",
          "answer_strategy": "technical_explanation",
          "confidence": 0.95,
          "reason": "Complete interviewer question."
        }
        """
        return LLMChatResult(content: content, modelName: "context-isolation-detector", providerKind: .deepSeek, providerName: "DeepSeek", baseURL: "", latencyMS: 5, isLocal: false, rawResponse: content)
    }

    private func currentQuestion(from prompt: String) -> String {
        if let range = prompt.range(of: #"CURRENT QUESTION TO ANSWER:\s*\n"([^"]+)""#, options: [.regularExpression, .caseInsensitive]) {
            return String(prompt[range])
                .replacingOccurrences(of: "CURRENT QUESTION TO ANSWER:", with: "", options: .caseInsensitive)
                .replacingOccurrences(of: "\"", with: "")
                .trimmingCharacters(in: .whitespacesAndNewlines)
        }
        if let range = prompt.range(of: #"CURRENT INTERVIEW QUESTION:\s*\n"([^"]+)""#, options: [.regularExpression, .caseInsensitive]) {
            return String(prompt[range])
                .replacingOccurrences(of: "CURRENT INTERVIEW QUESTION:", with: "", options: .caseInsensitive)
                .replacingOccurrences(of: "\"", with: "")
                .trimmingCharacters(in: .whitespacesAndNewlines)
        }
        return prompt
    }

    private func sayFirst(for question: String) -> String {
        let lower = question.lowercased()
        if lower.contains("diffusion") || lower.contains("autoregressive") {
            return "The diffusion policy performed better because it produced smoother continuous actions, handled the action distribution more robustly than the autoregressive and flow-matching variants, and reached seven out of ten successful grasps."
        }
        if lower.contains("fragile") || lower.contains("real robot execution") {
            return "The most fragile part was the real robot integration, where noisy perception, localisation instability, and timing between navigation and manipulation made the pipeline less predictable."
        }
        if lower.contains("about yourself") || lower.contains("robotics") {
            return "I am studying MSc Robotics at the University of Manchester, and my computer science background led me toward robotics because it combines software, perception, control, and real-world systems."
        }
        if lower.contains("join our team") || lower.contains("this role") {
            return "I want this role because it connects with my robotics, perception, AI, and real robot deployment interests while helping me grow as an engineer."
        }
        return "I would answer this current question directly and keep it specific to the interviewer prompt."
    }

    private func keyPoint(for question: String) -> String {
        String(sayFirst(for: question).prefix(90))
    }

    private func sectionAnswer(for question: String) -> [String] {
        [
            "STRATEGY:\nDirect answer\n",
            "SAY_FIRST:\n\(sayFirst(for: question))\n",
            "KEY_POINTS:\n",
            "- \(keyPoint(for: question))\n",
            "- Current-question specific\n",
            "FOLLOW_UP_READY:\n",
            "- I can go deeper if useful.\n",
            "CAUTION:\nNone\n"
        ]
    }

    private static func jsonString(_ value: String) -> String {
        guard let data = try? JSONEncoder().encode(value),
              let encoded = String(data: data, encoding: .utf8) else {
            return "\"\""
        }
        return encoded
    }

    private static func jsonEscaped(_ value: String) -> String {
        let encoded = jsonString(value)
        return String(encoded.dropFirst().dropLast())
    }
}

private final class ContextIsolationRetrievalService: ContextRetrievalService, @unchecked Sendable {
    struct Query: Equatable {
        var question: String
        var intent: QuestionIntent
    }

    private let lock = NSLock()
    private var recordedQueries: [Query] = []

    var queries: [Query] {
        lock.withLock { recordedQueries }
    }

    static let context = RetrievedContext(
        cvChunks: [
            chunk("fragility", "LeoRover pipeline fragility: noisy perception, localisation instability, timing mismatch, and real robot execution made the ROS2 navigation/manipulation pipeline less predictable.", .cv),
            chunk("diffusion", "VLA MuJoCo policy comparison: diffusion outperformed autoregressive and flow-matching decoders with smoother continuous actions, better robustness, and seven out of ten successful grasps.", .cv)
        ],
        jobDescriptionChunks: [
            chunk("jd", "Robotics software role involving perception, deployment, reliability, and evaluation.", .jobDescription)
        ]
    )

    func retrieveContextWithTrace(
        question: String,
        intent: QuestionIntent,
        maxCVWords: Int,
        maxJDWords: Int,
        strategy: AnswerStrategy?
    ) async throws -> (context: RetrievedContext, trace: RetrievalTrace) {
        lock.withLock {
            recordedQueries.append(Query(question: question, intent: intent))
        }
        let retrieved = Self.context
        let ranked = retrieved.cvChunks.map { chunk in
            RetrievedChunk(
                id: chunk.id,
                documentID: chunk.documentID,
                documentType: chunk.documentType,
                chunkIndex: chunk.chunkIndex,
                contentPreview: String(chunk.content.prefix(80)),
                fullContent: chunk.content,
                keywords: chunk.keywords,
                score: 1.0,
                keywordOverlapCount: 1,
                contentOverlapCount: 1,
                rank: 1,
                isIncludedInPrompt: true,
                sectionTitle: chunk.sectionTitle,
                wordCount: chunk.wordCount
            )
        }
        let trace = RetrievalTrace(
            id: UUID(),
            query: question,
            intent: intent.rawValue,
            createdAt: Date(),
            rankedCVChunks: ranked,
            rankedJDChunks: [],
            includedCVChunks: ranked,
            includedJDChunks: [],
            excludedCVChunks: [],
            excludedJDChunks: [],
            cvWordsUsed: 0,
            jdWordsUsed: 0,
            cvWordBudget: maxCVWords,
            jdWordBudget: maxJDWords,
            retrievalLatencyMS: 0,
            emptyQueryFallbackUsed: false,
            zeroScoreFallbackUsed: false
        )
        return (retrieved, trace)
    }

    private static func chunk(_ id: String, _ content: String, _ type: DocumentType) -> DocumentChunk {
        DocumentChunk(
            id: id,
            documentID: "\(type.rawValue)-doc",
            documentType: type,
            chunkIndex: 0,
            content: content,
            keywords: TextChunker.tokenize(content),
            sectionTitle: id,
            wordCount: content.split(whereSeparator: \.isWhitespace).count,
            metadataJSON: nil,
            createdAt: Date()
        )
    }
}
