import Foundation
import Testing
@testable import InterviewCopilotMac

@Suite(.serialized)
@MainActor
struct GenerationUIStateTests {
    @Test
    func firstVisibleFallbackClearsBlockingLoading() async throws {
        let (appState, session, question, delayProvider) = try makeAppState(
            client: StreamingMockLLMClient(),
            contextRetrievalService: SlowGenerationContextRetrievalService(delayNanoseconds: 5_000_000_000)
        )
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 5_000_000_000

        let task = Task {
            try await appState.generateSuggestion(
                for: question,
                session: session,
                transcript: question.questionText,
                autoGenerated: true
            )
        }
        defer { task.cancel() }

        try await waitUntil(timeout: 8.0) {
            appState.currentSuggestion != nil
        }

        #expect(appState.visibleAnswerExists)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(!appState.isActionLoading(ActionID.generateAnswer))
        #expect(appState.generationUIState.displayName == "Showing fallback")
        #expect(appState.currentGenerationTelemetry.firstVisibleAt != nil)
        #expect(appState.currentGenerationTelemetry.fallbackShownAt != nil)
    }

    @Test
    func fullCardWatchdogStopsExpansionSpinnerAndKeepsVisibleAnswer() async throws {
        let client = DeterministicGenerationLLMClient()
        client.stageBStreamNeverFinishes = true
        let (appState, session, question, delayProvider) = try makeAppState(client: client)
        delayProvider.sleepDuration = 5_000_000_000
        appState.generationFullCardWatchdogNanoseconds = 200_000_000

        try await appState.generateSuggestion(
            for: question,
            session: session,
            transcript: question.questionText,
            autoGenerated: false
        )

        try await waitUntil(timeout: 8.0) {
            appState.visibleAnswerExists &&
            !appState.shouldShowBlockingAnswerSpinner &&
            !appState.isActionLoading(ActionID.generateAnswer)
        }

        #expect(appState.visibleAnswerExists)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(!appState.isStreamingSayFirst)
        if appState.generationUIState.isTerminal {
            #expect(!appState.isExpandingSuggestionCard)
            #expect(["timed_out", "cancelled"].contains(appState.currentSuggestion?.stageBStatus ?? ""))
        } else {
            #expect(appState.shouldShowAnswerExpansionStatus)
        }
        #expect(!appState.isActionLoading(ActionID.generateAnswer))
    }

    @Test
    func jsonParseFailureStillProducesVisibleFallbackCard() async throws {
        let client = DeterministicGenerationLLMClient()
        client.fullCardContent = "I can explain the project clearly. - Problem and constraints. - Result and learning."

        let database = try TestSupport.makeTemporaryDatabase(prefix: "GenerationUIStateJSONTests")
        let settingsRepository = SettingsRepository(database: database)
        try settingsRepository.ensureDefaultProviderConfigurations()
        if let deepSeek = try settingsRepository.providerConfigurations().first(where: { $0.kind == .deepSeek }) {
            try settingsRepository.setActiveRealtimeProvider(id: deepSeek.id)
        }
        let router = LLMRouter(settingsRepository: settingsRepository, clients: [.deepSeek: client])
        let service = SuggestionGenerationService(llmRouter: router)
        let question = DetectedQuestion(
            id: UUID().uuidString,
            sessionID: UUID().uuidString,
            questionText: "What is your project?",
            intent: .projectDeepDive,
            answerStrategy: .projectWalkthrough,
            confidence: 0.95,
            shouldTrigger: true,
            questionComplete: true,
            modelName: "mock",
            promptVersion: "test",
            createdAt: Date()
        )

        let result = try await service.generateFullCard(
            question: question,
            context: RetrievedContext(cvChunks: [], jobDescriptionChunks: []),
            transcriptContext: question.questionText,
            sessionID: question.sessionID,
            cvSummary: "None",
            jdSummary: "None"
        )

        #expect(!result.card.sayFirst.isEmpty)
        #expect(result.card.caution?.localizedCaseInsensitiveContains("non-JSON") == true)
    }

    @Test
    func databasePersistenceFailureDoesNotHideVisibleAnswer() async throws {
        let client = DeterministicGenerationLLMClient()
        client.fullCardContent = """
        {
          "strategy": "Project Walkthrough",
          "say_first": "I can walk through the project by explaining the problem, my implementation choices, and the result.",
          "key_points": ["Problem and constraints", "Implementation choices", "Result and learning"],
          "follow_up_ready": ["I can go deeper on tradeoffs if helpful."],
          "confidence": 0.82,
          "caution": "None",
          "evidence_used": [],
          "risk_level": "low"
        }
        """

        let (appState, session, question, delayProvider) = try makeAppState(client: client)
        delayProvider.sleepDuration = 5_000_000_000
        appState.generationFullCardWatchdogNanoseconds = 5_000_000_000
        appState.simulateSuggestionPersistenceFailure = true

        try await appState.generateSuggestion(
            for: question,
            session: session,
            transcript: question.questionText,
            autoGenerated: false
        )

        try await waitUntil(timeout: 8.0) {
            appState.currentGenerationTelemetry.dbError != nil
        }

        #expect(appState.visibleAnswerExists)
        #expect(appState.currentSuggestion != nil)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(!appState.isActionLoading(ActionID.generateAnswer))
    }

    @Test
    func secondQuestionAfterFirstAnswerReadyDoesNotWaitForDelayedDBPersistence() async throws {
        let client = ConsecutiveQuestionLLMClient()
        let (appState, session, firstQuestion, delayProvider) = try makeAppState(client: client)
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "What is your second project?",
            suffix: "second-after-db-delay"
        )
        try appState.suggestionRepository.saveDetectedQuestion(secondQuestion)
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000
        appState.simulatedSuggestionPersistenceDelayNanoseconds = 5_000_000_000

        let firstTask = Task {
            try await appState.generateSuggestion(
                for: firstQuestion,
                session: session,
                transcript: firstQuestion.questionText,
                autoGenerated: true
            )
        }
        try await waitUntil(timeout: 8.0) {
            appState.currentSuggestion?.questionID == firstQuestion.id &&
            appState.visibleAnswerExists &&
            !appState.shouldShowBlockingAnswerSpinner
        }

        let secondTask = Task {
            try await appState.generateSuggestion(
                for: secondQuestion,
                session: session,
                transcript: secondQuestion.questionText,
                autoGenerated: true
            )
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == secondQuestion.id &&
            appState.currentSuggestion?.questionID == secondQuestion.id &&
            appState.visibleAnswerExists
        }

        #expect(appState.currentSuggestion?.questionID == secondQuestion.id)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(appState.cancelledGenerationCount >= 1)
        #expect(appState.lastSQLiteOperation != "None")
    }

    @Test
    func mainThreadHeartbeatAndTaskSummaryUpdateDuringGeneration() async throws {
        let (appState, session, question, delayProvider) = try makeAppState(
            client: StreamingMockLLMClient(),
            contextRetrievalService: SlowGenerationContextRetrievalService(delayNanoseconds: 1_000_000_000)
        )
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000
        appState.startMainThreadHeartbeat()

        let task = Task {
            try await appState.generateSuggestion(
                for: question,
                session: session,
                transcript: question.questionText,
                autoGenerated: true
            )
        }
        defer { task.cancel() }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == question.id &&
            appState.lastGenerationStateChangeAt != nil
        }
        try await Task.sleep(nanoseconds: 650_000_000)

        #expect(appState.mainThreadHeartbeatAt != nil)
        #expect(appState.mainThreadHeartbeatDelayMs < 2_000)
        #expect(appState.activeTaskSummary.localizedCaseInsensitiveContains("generation"))
        #expect(appState.lastRAGOperation.localizedCaseInsensitiveContains("retrieval"))
    }

    @Test
    func secondQuestionBeforeFirstTokenCancelsFirstAndShowsSecondFallback() async throws {
        let client = ConsecutiveQuestionLLMClient()
        client.stageADelayByQuestion = [
            "first project": 2_000_000_000,
            "second project": 2_000_000_000
        ]
        let (appState, session, firstQuestion, delayProvider) = try makeAppState(client: client)
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "What is your second project?",
            suffix: "second"
        )
        try appState.suggestionRepository.saveDetectedQuestion(secondQuestion)
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000

        let firstTask = Task {
            try await appState.generateSuggestion(
                for: firstQuestion,
                session: session,
                transcript: firstQuestion.questionText,
                autoGenerated: true
            )
        }
        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == firstQuestion.id &&
            appState.fallbackWatchdogActive
        }
        let firstGenerationID = try #require(appState.activeGenerationID)

        let secondTask = Task {
            try await appState.generateSuggestion(
                for: secondQuestion,
                session: session,
                transcript: secondQuestion.questionText,
                autoGenerated: true
            )
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == secondQuestion.id &&
            appState.currentSuggestion?.questionID == secondQuestion.id &&
            appState.visibleAnswerExists
        }

        #expect(appState.previousGenerationID == firstGenerationID)
        #expect(appState.cancelledGenerationCount >= 1)
        #expect(appState.currentSuggestion?.questionID == secondQuestion.id)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(appState.currentGenerationTelemetry.questionID == secondQuestion.id)
    }

    @Test
    func secondQuestionDuringFirstStageBPreventsOldStageBOverwrite() async throws {
        let client = ConsecutiveQuestionLLMClient()
        client.stageBDelayByQuestion = [
            "first project": 400_000_000,
            "second project": 1_500_000_000
        ]
        let (appState, session, firstQuestion, delayProvider) = try makeAppState(client: client)
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "What is your second project?",
            suffix: "second-stage-b"
        )
        try appState.suggestionRepository.saveDetectedQuestion(secondQuestion)
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000

        let firstTask = Task {
            try await appState.generateSuggestion(
                for: firstQuestion,
                session: session,
                transcript: firstQuestion.questionText,
                autoGenerated: true
            )
        }
        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == firstQuestion.id &&
            appState.stageBTaskActive
        }

        let secondTask = Task {
            try await appState.generateSuggestion(
                for: secondQuestion,
                session: session,
                transcript: secondQuestion.questionText,
                autoGenerated: true
            )
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == secondQuestion.id &&
            appState.currentSuggestion?.questionID == secondQuestion.id &&
            appState.visibleAnswerExists
        }
        try await Task.sleep(nanoseconds: 700_000_000)

        #expect(appState.currentSuggestion?.questionID == secondQuestion.id)
        #expect(!appState.currentSuggestion!.sayFirst.localizedCaseInsensitiveContains("first project"))
        #expect(!appState.shouldShowBlockingAnswerSpinner)
    }

    @Test
    func hangingFirstProviderStreamDoesNotStealSecondQuestionWatchdog() async throws {
        let client = ConsecutiveQuestionLLMClient()
        client.hangingStageAQuestions = ["first project"]
        client.stageADelayByQuestion = ["second project": 2_000_000_000]
        let (appState, session, firstQuestion, delayProvider) = try makeAppState(client: client)
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "What is your second project?",
            suffix: "second-hang"
        )
        try appState.suggestionRepository.saveDetectedQuestion(secondQuestion)
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000

        let firstTask = Task {
            try await appState.generateSuggestion(
                for: firstQuestion,
                session: session,
                transcript: firstQuestion.questionText,
                autoGenerated: true
            )
        }
        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == firstQuestion.id &&
            appState.providerStreamActive
        }

        let secondTask = Task {
            try await appState.generateSuggestion(
                for: secondQuestion,
                session: session,
                transcript: secondQuestion.questionText,
                autoGenerated: true
            )
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == secondQuestion.id &&
            appState.currentSuggestion?.questionID == secondQuestion.id &&
            appState.visibleAnswerExists
        }

        #expect(appState.currentSuggestion?.questionID == secondQuestion.id)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(appState.cancelledGenerationCount >= 1)
    }

    @Test
    func duplicateSecondQuestionDoesNotLeaveSpinner() async throws {
        let (appState, _, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())

        #expect(appState.isDuplicateAutoQuestion(firstQuestion.questionText) == false)
        #expect(appState.isDuplicateAutoQuestion(firstQuestion.questionText) == true)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(!appState.isActionLoading(ActionID.generateAnswer))
        #expect(appState.duplicateSuppressionCount >= 1)
    }

    @Test
    func rapidThreeQuestionSequenceLeavesOnlyLatestQuestionActive() async throws {
        let client = ConsecutiveQuestionLLMClient()
        client.stageADelayByQuestion = [
            "first project": 1_000_000_000,
            "second project": 1_000_000_000,
            "third project": 1_000_000_000
        ]
        let (appState, session, firstQuestion, delayProvider) = try makeAppState(client: client)
        let secondQuestion = try makeQuestion(sessionID: session.id, text: "What is your second project?", suffix: "second-rapid")
        let thirdQuestion = try makeQuestion(sessionID: session.id, text: "What is your third project?", suffix: "third-rapid")
        try appState.suggestionRepository.saveDetectedQuestion(secondQuestion)
        try appState.suggestionRepository.saveDetectedQuestion(thirdQuestion)
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 400_000_000

        let firstTask = Task {
            try await appState.generateSuggestion(for: firstQuestion, session: session, transcript: firstQuestion.questionText, autoGenerated: true)
        }
        try await waitUntil(timeout: 8.0) { appState.activeQuestionID == firstQuestion.id }

        let secondTask = Task {
            try await appState.generateSuggestion(for: secondQuestion, session: session, transcript: secondQuestion.questionText, autoGenerated: true)
        }
        try await waitUntil(timeout: 8.0) { appState.activeQuestionID == secondQuestion.id }

        let thirdTask = Task {
            try await appState.generateSuggestion(for: thirdQuestion, session: session, transcript: thirdQuestion.questionText, autoGenerated: true)
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
            thirdTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == thirdQuestion.id &&
            appState.currentSuggestion?.questionID == thirdQuestion.id &&
            appState.visibleAnswerExists
        }

        #expect(appState.currentSuggestion?.questionID == thirdQuestion.id)
        #expect(appState.currentGenerationTelemetry.questionID == thirdQuestion.id)
        #expect(appState.cancelledGenerationCount >= 2)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
    }

    private func makeAppState(
        client: any LLMClientProtocol,
        contextRetrievalService: ContextRetrievalService? = nil
    ) throws -> (AppState, InterviewSession, DetectedQuestion, MockDelayProvider) {
        let database = try TestSupport.makeTemporaryDatabase(prefix: "GenerationUIStateTests")
        let settingsRepository = SettingsRepository(database: database)
        try settingsRepository.ensureDefaultProviderConfigurations()
        if let deepSeek = try settingsRepository.providerConfigurations().first(where: { $0.kind == .deepSeek }) {
            try settingsRepository.setActiveRealtimeProvider(id: deepSeek.id)
        }

        let router = LLMRouter(settingsRepository: settingsRepository, clients: [.deepSeek: client])
        let appState = AppState(
            database: database,
            llmRouter: router,
            contextRetrievalService: contextRetrievalService
        )
        let delayProvider = MockDelayProvider()
        appState.delayProvider = delayProvider

        let session = try appState.sessionRepository.createSession(mode: .microphone)
        appState.currentSession = session

        let question = DetectedQuestion(
            id: UUID().uuidString,
            sessionID: session.id,
            transcriptSegmentID: nil,
            questionText: "What is your project?",
            intent: .projectDeepDive,
            answerStrategy: .projectWalkthrough,
            confidence: 0.95,
            reason: "Test",
            shouldTrigger: true,
            questionComplete: true,
            modelName: "mock",
            promptVersion: "test",
            createdAt: Date()
        )
        try appState.suggestionRepository.saveDetectedQuestion(question)
        return (appState, session, question, delayProvider)
    }

    private func makeQuestion(sessionID: String, text: String, suffix: String) throws -> DetectedQuestion {
        DetectedQuestion(
            id: "question-\(suffix)-\(UUID().uuidString)",
            sessionID: sessionID,
            transcriptSegmentID: nil,
            questionText: text,
            intent: .projectDeepDive,
            answerStrategy: .projectWalkthrough,
            confidence: 0.95,
            reason: "Test",
            shouldTrigger: true,
            questionComplete: true,
            modelName: "mock",
            promptVersion: "test",
            createdAt: Date()
        )
    }

    private func waitUntil(timeout: TimeInterval, predicate: @escaping @MainActor () -> Bool) async throws {
        let start = Date()
        while !predicate() {
            if Date().timeIntervalSince(start) > timeout {
                throw NSError(
                    domain: "GenerationUIStateTests",
                    code: 1,
                    userInfo: [NSLocalizedDescriptionKey: "Timed out waiting for generation UI state."]
                )
            }
            try await Task.sleep(nanoseconds: 50_000_000)
        }
    }
}

private final class DeterministicGenerationLLMClient: LLMClientProtocol {
    let providerKind: LLMProviderKind = .deepSeek
    var fullCardContent = """
    {
      "strategy": "Project Walkthrough",
      "say_first": "I can explain the project by describing the problem, the implementation choices, and the result.",
      "key_points": ["Problem and constraints", "Implementation choices", "Result and learning"],
      "follow_up_ready": ["I can explain the tradeoffs if useful."],
      "confidence": 0.8,
      "caution": "None",
      "evidence_used": [],
      "risk_level": "low"
    }
    """
    var fullCardDelayNS: UInt64 = 0
    var stageBStreamNeverFinishes = false

    func testConnection(configuration: LLMProviderConfiguration) async throws -> LLMConnectionTestResult {
        LLMConnectionTestResult(success: true, message: "Mock OK", latencyMS: 0, models: [])
    }

    func chatCompletion(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) async throws -> LLMChatResult {
        if fullCardDelayNS > 0 {
            try await Task.sleep(nanoseconds: fullCardDelayNS)
        }
        return LLMChatResult(
            content: fullCardContent,
            modelName: "mock-model",
            providerKind: .deepSeek,
            providerName: "DeepSeek",
            baseURL: "",
            latencyMS: 100,
            isLocal: false,
            rawResponse: fullCardContent
        )
    }

    func chatCompletionStream(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) -> AsyncThrowingStream<String, Error> {
        let promptText = messages.map(\.content).joined(separator: "\n")
        let isStageBSectionStream = promptText.contains("Return plain text sections only")
        let hangsStageBStream = stageBStreamNeverFinishes
        return AsyncThrowingStream { continuation in
            Task {
                if isStageBSectionStream {
                    if hangsStageBStream {
                        try? await Task.sleep(nanoseconds: 60_000_000_000)
                    }
                    continuation.finish()
                    return
                }
                for token in ["I ", "built ", "a ", "robotics ", "project."] {
                    continuation.yield(token)
                }
                continuation.finish()
            }
        }
    }

    func listModels(configuration: LLMProviderConfiguration) async throws -> [LLMModelInfo] {
        []
    }
}

private final class ConsecutiveQuestionLLMClient: LLMClientProtocol, @unchecked Sendable {
    let providerKind: LLMProviderKind = .deepSeek
    var stageADelayByQuestion = [String: UInt64]()
    var stageBDelayByQuestion = [String: UInt64]()
    var hangingStageAQuestions = Set<String>()

    func testConnection(configuration: LLMProviderConfiguration) async throws -> LLMConnectionTestResult {
        LLMConnectionTestResult(success: true, message: "Mock OK", latencyMS: 0, models: [])
    }

    func chatCompletion(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) async throws -> LLMChatResult {
        let questionKey = questionKey(from: messages)
        if let delay = stageBDelayByQuestion[questionKey] {
            try? await Task.sleep(nanoseconds: delay)
        }
        let content = fullCardJSON(for: questionKey)
        return LLMChatResult(
            content: content,
            modelName: "mock-model",
            providerKind: .deepSeek,
            providerName: "DeepSeek",
            baseURL: "",
            latencyMS: 100,
            isLocal: false,
            rawResponse: content
        )
    }

    func chatCompletionStream(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) -> AsyncThrowingStream<String, Error> {
        let promptText = messages.map(\.content).joined(separator: "\n")
        let questionKey = questionKey(from: messages)
        let isStageB = promptText.contains("Return plain text sections only")
        let stageADelay = stageADelayByQuestion[questionKey] ?? 0
        let stageBDelay = stageBDelayByQuestion[questionKey] ?? 0
        let hangs = hangingStageAQuestions.contains(questionKey) && !isStageB

        return AsyncThrowingStream { continuation in
            let task = Task {
                if hangs {
                    try? await Task.sleep(nanoseconds: 60_000_000_000)
                    continuation.finish()
                    return
                }
                if isStageB {
                    if stageBDelay > 0 {
                        try? await Task.sleep(nanoseconds: stageBDelay)
                    }
                    for token in stageBSections(for: questionKey) {
                        if Task.isCancelled {
                            continuation.finish()
                            return
                        }
                        continuation.yield(token)
                    }
                    continuation.finish()
                    return
                }
                if stageADelay > 0 {
                    try? await Task.sleep(nanoseconds: stageADelay)
                }
                for token in ["I ", "can ", "walk ", "through ", "my ", "\(questionKey) ", "clearly."] {
                    if Task.isCancelled {
                        continuation.finish()
                        return
                    }
                    continuation.yield(token)
                }
                continuation.finish()
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    func listModels(configuration: LLMProviderConfiguration) async throws -> [LLMModelInfo] {
        []
    }

    private func questionKey(from messages: [LLMChatMessage]) -> String {
        let promptText = messages.map(\.content).joined(separator: "\n").lowercased()
        if promptText.contains("third project") {
            return "third project"
        }
        if promptText.contains("second project") {
            return "second project"
        }
        return "first project"
    }

    private func fullCardJSON(for questionKey: String) -> String {
        """
        {
          "strategy": "Project Walkthrough",
          "say_first": "I can explain my \(questionKey) by covering the problem, my implementation choices, and the result.",
          "key_points": ["Problem for \(questionKey)", "Implementation choices", "Result and learning"],
          "follow_up_ready": ["I can go deeper on tradeoffs if helpful."],
          "confidence": 0.82,
          "caution": "None",
          "evidence_used": [],
          "risk_level": "low"
        }
        """
    }

    private func stageBSections(for questionKey: String) -> [String] {
        [
            "Strategy: Project Walkthrough\n",
            "Say First: I can explain my \(questionKey) by covering the problem, my implementation choices, and the result.\n",
            "Key Points:\n",
            "- Problem for \(questionKey)\n",
            "- Implementation choices\n",
            "- Result and learning\n",
            "Follow-up Ready:\n",
            "- I can go deeper on tradeoffs if helpful.\n",
            "Caution: None\n"
        ]
    }
}

private final class SlowGenerationContextRetrievalService: ContextRetrievalService {
    let delayNanoseconds: UInt64

    init(delayNanoseconds: UInt64) {
        self.delayNanoseconds = delayNanoseconds
    }

    func retrieveContextWithTrace(
        question: String,
        intent: QuestionIntent,
        maxCVWords: Int,
        maxJDWords: Int,
        strategy: AnswerStrategy?
    ) async throws -> (context: RetrievedContext, trace: RetrievalTrace) {
        try await Task.sleep(nanoseconds: delayNanoseconds)
        let context = RetrievedContext(cvChunks: [], jobDescriptionChunks: [])
        let trace = RetrievalTrace(
            id: UUID(),
            query: question,
            intent: intent.rawValue,
            createdAt: Date(),
            rankedCVChunks: [],
            rankedJDChunks: [],
            includedCVChunks: [],
            includedJDChunks: [],
            excludedCVChunks: [],
            excludedJDChunks: [],
            cvWordsUsed: 0,
            jdWordsUsed: 0,
            cvWordBudget: maxCVWords,
            jdWordBudget: maxJDWords,
            retrievalLatencyMS: Double(delayNanoseconds) / 1_000_000.0,
            emptyQueryFallbackUsed: false,
            zeroScoreFallbackUsed: false
        )
        return (context, trace)
    }
}
