import Combine
import Foundation
import Testing
@testable import InterviewCopilotMac

@Suite(.serialized)
@MainActor
struct GenerationUIStateTests {
    @Test
    func firstVisibleFallbackClearsBlockingLoading() async throws {
        let (appState, session, question, delayProvider) = try makeAppState(
            client: StreamingMockLLMClient(),
            contextRetrievalService: SlowGenerationContextRetrievalService(delayNanoseconds: 5_000_000_000),
            bindCandidateContext: true
        )
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 5_000_000_000

        let task = Task {
            try await appState.generateSuggestion(
                for: question,
                session: session,
                transcript: question.questionText,
                autoGenerated: true
            )
        }
        defer { task.cancel() }

        try await waitUntil(timeout: 8.0) {
            appState.currentSuggestion != nil
        }

        #expect(appState.visibleAnswerExists)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(!appState.isActionLoading(ActionID.generateAnswer))
        #expect(appState.generationUIState.displayName == "Showing fallback")
        #expect(appState.currentGenerationTelemetry.firstVisibleAt != nil)
        #expect(appState.currentGenerationTelemetry.fallbackShownAt != nil)
    }

    @Test
    func fullCardWatchdogStopsExpansionSpinnerAndKeepsVisibleAnswer() async throws {
        let client = DeterministicGenerationLLMClient()
        client.stageBStreamNeverFinishes = true
        let (appState, session, question, delayProvider) = try makeAppState(client: client, bindCandidateContext: true)
        delayProvider.sleepDuration = 5_000_000_000
        appState.generationFullCardWatchdogNanoseconds = 200_000_000

        try await appState.generateSuggestion(
            for: question,
            session: session,
            transcript: question.questionText,
            autoGenerated: false
        )

        try await waitUntil(timeout: 8.0) {
            appState.visibleAnswerExists &&
            !appState.shouldShowBlockingAnswerSpinner &&
            !appState.isActionLoading(ActionID.generateAnswer)
        }

        #expect(appState.visibleAnswerExists)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(!appState.isStreamingSayFirst)
        if appState.generationUIState.isTerminal {
            #expect(!appState.isExpandingSuggestionCard)
            #expect(["timed_out", "cancelled"].contains(appState.currentSuggestion?.stageBStatus ?? ""))
        } else {
            #expect(appState.shouldShowAnswerExpansionStatus)
        }
        #expect(!appState.isActionLoading(ActionID.generateAnswer))
    }

    @Test
    func jsonParseFailureStillProducesVisibleFallbackCard() async throws {
        let client = DeterministicGenerationLLMClient()
        client.fullCardContent = "I can explain the project clearly. - Problem and constraints. - Result and learning."

        let database = try TestSupport.makeTemporaryDatabase(prefix: "GenerationUIStateJSONTests")
        let settingsRepository = SettingsRepository(database: database)
        try settingsRepository.ensureDefaultProviderConfigurations()
        if let deepSeek = try settingsRepository.providerConfigurations().first(where: { $0.kind == .deepSeek }) {
            try settingsRepository.setActiveRealtimeProvider(id: deepSeek.id)
        }
        let router = LLMRouter(settingsRepository: settingsRepository, clients: [.deepSeek: client])
        let service = SuggestionGenerationService(llmRouter: router)
        let question = DetectedQuestion(
            id: UUID().uuidString,
            sessionID: UUID().uuidString,
            questionText: "Could you walk me through your first project, the LeoRover navigation pipeline?",
            intent: .projectDeepDive,
            answerStrategy: .projectWalkthrough,
            confidence: 0.95,
            shouldTrigger: true,
            questionComplete: true,
            modelName: "mock",
            promptVersion: "test",
            createdAt: Date()
        )

        let result = try await service.generateFullCard(
            question: question,
            context: RetrievedContext(cvChunks: [], jobDescriptionChunks: []),
            transcriptContext: question.questionText,
            sessionID: question.sessionID,
            cvSummary: "None",
            jdSummary: "None"
        )

        #expect(!result.card.sayFirst.isEmpty)
        #expect(result.card.caution?.localizedCaseInsensitiveContains("non-JSON") == true)
    }

    @Test
    func databasePersistenceFailureDoesNotHideVisibleAnswer() async throws {
        let client = DeterministicGenerationLLMClient()
        client.fullCardContent = """
        {
          "strategy": "Project Walkthrough",
          "say_first": "I can walk through the LeoRover project as an autonomous object retrieval robot, covering the ROS2 pipeline, YOLOv8 perception, navigation, manipulation, and what I learned from real robot execution.",
          "key_points": ["LeoRover autonomous object retrieval", "ROS2, YOLOv8 perception, navigation, and manipulation", "Real robot execution and reliability learning"],
          "follow_up_ready": ["I can go deeper on ROS2 navigation and manipulation tradeoffs if helpful."],
          "confidence": 0.82,
          "caution": "None",
          "evidence_used": [],
          "risk_level": "low"
        }
        """

        let (appState, session, question, delayProvider) = try makeAppState(client: client, bindCandidateContext: true)
        delayProvider.sleepDuration = 5_000_000_000
        appState.generationFullCardWatchdogNanoseconds = 5_000_000_000
        appState.simulateSuggestionPersistenceFailure = true

        try await appState.generateSuggestion(
            for: question,
            session: session,
            transcript: question.questionText,
            autoGenerated: false
        )

        try await waitUntil(timeout: 8.0) {
            appState.currentGenerationTelemetry.dbError != nil
        }

        #expect(appState.visibleAnswerExists)
        #expect(appState.currentSuggestion != nil)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(!appState.isActionLoading(ActionID.generateAnswer))
    }

    @Test
    func secondQuestionAfterFirstAnswerReadyDoesNotWaitForDelayedDBPersistence() async throws {
        let client = ConsecutiveQuestionLLMClient()
        let (appState, session, firstQuestion, delayProvider) = try makeAppState(client: client, bindCandidateContext: true)
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "Could you walk me through your second project, the LeoRover navigation pipeline?",
            suffix: "second-after-db-delay"
        )
        try appState.suggestionRepository.saveDetectedQuestion(secondQuestion)
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000
        appState.simulatedSuggestionPersistenceDelayNanoseconds = 5_000_000_000

        let firstTask = Task {
            try await appState.generateSuggestion(
                for: firstQuestion,
                session: session,
                transcript: firstQuestion.questionText,
                autoGenerated: true
            )
        }
        try await waitUntil(timeout: 8.0) {
            appState.currentSuggestion?.questionID == firstQuestion.id &&
            appState.visibleAnswerExists &&
            !appState.shouldShowBlockingAnswerSpinner
        }

        let secondTask = Task {
            try await appState.generateSuggestion(
                for: secondQuestion,
                session: session,
                transcript: secondQuestion.questionText,
                autoGenerated: true
            )
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == secondQuestion.id &&
            appState.currentSuggestion?.questionID == secondQuestion.id &&
            appState.visibleAnswerExists
        }

        #expect(appState.currentSuggestion?.questionID == secondQuestion.id)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(appState.cancelledGenerationCount >= 1)
        #expect(appState.lastSQLiteOperation != "None")
    }

    @Test
    func mainThreadHeartbeatAndTaskSummaryUpdateDuringGeneration() async throws {
        let (appState, session, question, delayProvider) = try makeAppState(
            client: StreamingMockLLMClient(),
            contextRetrievalService: SlowGenerationContextRetrievalService(delayNanoseconds: 1_000_000_000),
            bindCandidateContext: true
        )
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000
        appState.startMainThreadHeartbeat()

        let task = Task {
            try await appState.generateSuggestion(
                for: question,
                session: session,
                transcript: question.questionText,
                autoGenerated: true
            )
        }
        defer { task.cancel() }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == question.id &&
            appState.lastGenerationStateChangeAt != nil
        }
        try await Task.sleep(nanoseconds: 650_000_000)

        #expect(appState.mainThreadHeartbeatAt != nil)
        #expect(appState.mainThreadHeartbeatDelayMs < 2_000)
        #expect(appState.activeTaskSummary.localizedCaseInsensitiveContains("generation"))
        #expect(appState.lastRAGOperation.localizedCaseInsensitiveContains("retrieval"))
    }

    @Test
    func mainThreadHeartbeatDoesNotInvalidateProductUI() async throws {
        let (appState, _, _, _) = try makeAppState(client: StreamingMockLLMClient())
        appState.startMainThreadHeartbeat()
        try await Task.sleep(nanoseconds: 100_000_000)

        var publishedChangeCount = 0
        let subscription = appState.objectWillChange.sink {
            publishedChangeCount += 1
        }

        try await Task.sleep(nanoseconds: 650_000_000)

        #expect(appState.mainThreadHeartbeatAt != nil)
        #expect(appState.mainThreadHeartbeatDelayMs < 2_000)
        #expect(publishedChangeCount == 0)
        withExtendedLifetime(subscription) {}
    }

    @Test
    func secondQuestionBeforeFirstTokenCancelsFirstAndShowsSecondFallback() async throws {
        let client = ConsecutiveQuestionLLMClient()
        client.stageADelayByQuestion = [
            "first project": 2_000_000_000,
            "second project": 2_000_000_000
        ]
        let (appState, session, firstQuestion, delayProvider) = try makeAppState(client: client, bindCandidateContext: true)
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "Could you walk me through your second project, the LeoRover navigation pipeline?",
            suffix: "second"
        )
        try appState.suggestionRepository.saveDetectedQuestion(secondQuestion)
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000

        let firstTask = Task {
            try await appState.generateSuggestion(
                for: firstQuestion,
                session: session,
                transcript: firstQuestion.questionText,
                autoGenerated: true
            )
        }
        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == firstQuestion.id &&
            appState.fallbackWatchdogActive
        }
        let firstGenerationID = try #require(appState.activeGenerationID)

        let secondTask = Task {
            try await appState.generateSuggestion(
                for: secondQuestion,
                session: session,
                transcript: secondQuestion.questionText,
                autoGenerated: true
            )
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == secondQuestion.id &&
            appState.currentSuggestion?.questionID == secondQuestion.id &&
            appState.visibleAnswerExists
        }

        #expect(appState.previousGenerationID == firstGenerationID)
        #expect(appState.cancelledGenerationCount >= 1)
        #expect(appState.currentSuggestion?.questionID == secondQuestion.id)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(appState.currentGenerationTelemetry.questionID == secondQuestion.id)
    }

    @Test
    func secondQuestionDuringFirstStageBPreventsOldStageBOverwrite() async throws {
        let client = ConsecutiveQuestionLLMClient()
        client.stageBDelayByQuestion = [
            "first project": 400_000_000,
            "second project": 1_500_000_000
        ]
        let (appState, session, firstQuestion, delayProvider) = try makeAppState(client: client, bindCandidateContext: true)
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "Could you walk me through your second project, the LeoRover navigation pipeline?",
            suffix: "second-stage-b"
        )
        try appState.suggestionRepository.saveDetectedQuestion(secondQuestion)
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000

        let firstTask = Task {
            try await appState.generateSuggestion(
                for: firstQuestion,
                session: session,
                transcript: firstQuestion.questionText,
                autoGenerated: true
            )
        }
        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == firstQuestion.id &&
            appState.stageBTaskActive
        }

        let secondTask = Task {
            try await appState.generateSuggestion(
                for: secondQuestion,
                session: session,
                transcript: secondQuestion.questionText,
                autoGenerated: true
            )
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == secondQuestion.id &&
            appState.currentSuggestion?.questionID == secondQuestion.id &&
            appState.visibleAnswerExists
        }
        try await Task.sleep(nanoseconds: 700_000_000)

        #expect(appState.currentSuggestion?.questionID == secondQuestion.id)
        #expect(!appState.currentSuggestion!.sayFirst.localizedCaseInsensitiveContains("first project"))
        #expect(!appState.shouldShowBlockingAnswerSpinner)
    }

    @Test
    func hangingFirstProviderStreamDoesNotStealSecondQuestionWatchdog() async throws {
        let client = ConsecutiveQuestionLLMClient()
        client.hangingStageAQuestions = ["first project"]
        client.stageADelayByQuestion = ["second project": 2_000_000_000]
        let (appState, session, firstQuestion, delayProvider) = try makeAppState(client: client, bindCandidateContext: true)
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "Could you walk me through your second project, the LeoRover navigation pipeline?",
            suffix: "second-hang"
        )
        try appState.suggestionRepository.saveDetectedQuestion(secondQuestion)
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000

        let firstTask = Task {
            try await appState.generateSuggestion(
                for: firstQuestion,
                session: session,
                transcript: firstQuestion.questionText,
                autoGenerated: true
            )
        }
        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == firstQuestion.id &&
            appState.providerStreamActive
        }

        let secondTask = Task {
            try await appState.generateSuggestion(
                for: secondQuestion,
                session: session,
                transcript: secondQuestion.questionText,
                autoGenerated: true
            )
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == secondQuestion.id &&
            appState.currentSuggestion?.questionID == secondQuestion.id &&
            appState.visibleAnswerExists
        }

        #expect(appState.currentSuggestion?.questionID == secondQuestion.id)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(appState.cancelledGenerationCount >= 1)
    }

    @Test
    func duplicateSecondQuestionDoesNotLeaveSpinner() async throws {
        let (appState, _, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())

        #expect(appState.isDuplicateAutoQuestion(firstQuestion.questionText) == false)
        #expect(appState.isDuplicateAutoQuestion(firstQuestion.questionText) == true)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
        #expect(!appState.isActionLoading(ActionID.generateAnswer))
        #expect(appState.duplicateSuppressionCount >= 1)
    }

    @Test
    func streamingUpdateForNewQuestionReplacesMismatchedVisibleCardAtomically() throws {
        let (appState, session, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "Why do you want this role?",
            suffix: "atomic-second"
        )
        let generationID = "generation-atomic-second"
        appState.activateGeneration(
            question: secondQuestion,
            generationID: generationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        #expect(appState.activeGenerationController?.identity.acceptedQuestionID == secondQuestion.id)
        #expect(appState.activeGenerationController?.identity.generationID == generationID)
        #expect(appState.activeGenerationController?.identity.sessionID == session.id)
        #expect(appState.activeGenerationController?.identity.questionText == secondQuestion.questionText)
        #expect(appState.activeGenerationController?.identity.promptPrimaryQuestion == secondQuestion.questionText)
        appState.lastDetectedQuestion = secondQuestion

        var staleCard = SuggestionCard(
            id: "stale-first-card",
            sessionID: session.id,
            questionID: firstQuestion.id,
            strategy: "Project Walkthrough",
            sayFirst: "I can describe my first project clearly.",
            keyPoints: ["First project"],
            followUpReady: [],
            confidence: 0.8,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .low,
            modelName: "mock",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )
        staleCard.questionText = firstQuestion.questionText
        staleCard.promptPrimaryQuestion = firstQuestion.questionText
        staleCard.generationID = "generation-first"
        appState.currentSuggestion = staleCard

        let sections = StreamingSuggestionSections(
            strategy: "Role motivation",
            sayFirst: "I want this role because it connects my robotics, AI, perception, and real-world deployment experience with a team where I can contribute and grow.",
            keyPoints: ["Robotics and AI fit", "Real-world deployment interest"],
            followUpReady: [],
            caution: ""
        )
        appState.publishStreamingSections(
            sections,
            cardID: "second-card",
            generationID: generationID,
            question: secondQuestion,
            session: session,
            requestStart: Date(),
            stageBStreamStartedMS: nil
        )

        let visible = try #require(appState.currentSuggestion)
        #expect(visible.detectedQuestionID == secondQuestion.id)
        #expect(visible.questionText == secondQuestion.questionText)
        #expect(visible.promptPrimaryQuestion == secondQuestion.questionText)
        #expect(visible.generationID == generationID)
        #expect(visible.sayFirst.localizedCaseInsensitiveContains("this role"))
        #expect(!visible.sayFirst.localizedCaseInsensitiveContains("first project"))
        #expect(appState.currentQABinding.bindingStatus == .matched)
    }

    @Test
    func stageBStalePlanCannotOverwriteCurrentQuestionCard() async throws {
        let (appState, session, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let traceURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("stale-stage-b-\(UUID().uuidString).jsonl")
        appState.runtimeTranscriptTraceLogURL = traceURL
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "Why do you want this role?",
            suffix: "stage-b-atomic-second"
        )
        let generationID = "generation-stage-b-second"
        appState.activateGeneration(
            question: secondQuestion,
            generationID: generationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        appState.lastDetectedQuestion = secondQuestion
        var secondCard = SuggestionCard(
            id: "second-visible-card",
            sessionID: session.id,
            questionID: secondQuestion.id,
            strategy: "Role motivation",
            sayFirst: "I want this role because it connects with my robotics and deployed AI systems experience.",
            keyPoints: ["Robotics fit"],
            followUpReady: [],
            confidence: 0.8,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .low,
            modelName: "mock",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )
        secondCard.questionText = secondQuestion.questionText
        secondCard.promptPrimaryQuestion = secondQuestion.questionText
        secondCard.generationID = generationID
        appState.currentSuggestion = secondCard

        let stalePlan = StageBApplicationPlan(
            generationID: "generation-stage-b-first",
            detectedQuestionID: firstQuestion.id,
            action: .applyFullCard,
            fallbackReason: nil,
            shouldPersist: true,
            shouldUpdateVisibleCard: true,
            safeDiagnostics: [:]
        )
        let staleSections = StreamingSuggestionSections(
            strategy: "Project Walkthrough",
            sayFirst: "I can explain my first project by covering the problem, choices, and result.",
            keyPoints: ["First project details"],
            followUpReady: [],
            caution: ""
        )

        try await appState.applyStageBApplicationPlan(
            stalePlan,
            sections: staleSections,
            cardID: "stale-stage-b-card",
            generationID: stalePlan.generationID,
            question: firstQuestion,
            session: session,
            requestStart: Date(),
            stageBStreamStartedMS: nil,
            retrievedChunks: [],
            triggerPath: .autoDetect,
            source: .systemAudio,
            speaker: .interviewer,
            preserveFallbackSayFirst: false
        )

        let visible = try #require(appState.currentSuggestion)
        #expect(visible.detectedQuestionID == secondQuestion.id)
        #expect(visible.questionText == secondQuestion.questionText)
        #expect(visible.sayFirst.localizedCaseInsensitiveContains("first project") == false)
        #expect(appState.staleAnswerDiscardCount >= 1)
        try await waitForTraceEvent("currentCardRegressionRejected", at: traceURL)
        let trace = try String(contentsOf: traceURL, encoding: .utf8)
        #expect(trace.contains("\"event_type\":\"staleGenerationResultRejected\""))
        #expect(trace.contains("\"event_type\":\"currentCardRegressionRejected\""))
        #expect(trace.contains("\"old_generation_id\":\"generation-stage-b-first\""))
        #expect(trace.contains("\"current_generation_id\":\"\(generationID)\""))
        #expect(trace.contains("\"old_question_text\":\"\(firstQuestion.questionText)\""))
        #expect(trace.contains("\"current_question_text\":\"\(secondQuestion.questionText)\""))
        #expect(trace.contains("\"old_accepted_question_id\":\"\(firstQuestion.id)\""))
        #expect(trace.contains("\"current_accepted_question_id\":\"\(secondQuestion.id)\""))
        #expect(trace.contains("\"source_callback\":\"stage_b_application\""))
    }

    @Test
    func stageBRejectionKeepsAcceptedProviderCardInsteadOfInventingFallback() async throws {
        let (appState, session, _, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let question = try makeQuestion(
            sessionID: session.id,
            text: "What made real-world execution on the LeoRover harder than a clean simulation or demo environment?",
            suffix: "stage-b-semantic-fallback"
        )
        try appState.suggestionRepository.saveDetectedQuestion(question)
        let generationID = "generation-stage-b-semantic-fallback"
        appState.activateGeneration(
            question: question,
            generationID: generationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        appState.lastDetectedQuestion = question

        var currentProviderCard = SuggestionCard(
            id: "current-provider-card",
            sessionID: session.id,
            questionID: question.id,
            strategy: "DeepSeek",
            sayFirst: "A clean simulation keeps timing, calibration, and module integration controlled, while detections can be noisy and recovery is needed.",
            keyPoints: ["Simulation is controlled.", "Noise and calibration matter.", "Recovery behaviour is needed."],
            followUpReady: [],
            confidence: 0.8,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .medium,
            modelName: "deepseek",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )
        currentProviderCard.questionText = question.questionText
        currentProviderCard.promptPrimaryQuestion = question.questionText
        currentProviderCard.generationID = generationID
        currentProviderCard.sayFirstSource = "deepseek_stream"
        currentProviderCard.finalVisibleSource = "deepseek_stream"
        currentProviderCard.stageBCompleted = true
        currentProviderCard.stageBStatus = "completed"
        appState.currentSuggestion = currentProviderCard

        let plan = StageBApplicationPlan(
            generationID: generationID,
            detectedQuestionID: question.id,
            action: .useSemanticFallback,
            fallbackReason: "semantic mismatch",
            shouldPersist: true,
            shouldUpdateVisibleCard: true,
            safeDiagnostics: [:],
            identity: GenerationIdentity(question: question, generationID: generationID, contextSnapshotID: session.contextSnapshotID)
        )
        let sections = StreamingSuggestionSections(
            strategy: "DeepSeek",
            sayFirst: currentProviderCard.sayFirst,
            keyPoints: currentProviderCard.keyPoints,
            followUpReady: [],
            caution: ""
        )

        try await appState.applyStageBApplicationPlan(
            plan,
            sections: sections,
            cardID: "semantic-stage-b-card",
            generationID: generationID,
            question: question,
            session: session,
            requestStart: Date(),
            stageBStreamStartedMS: nil,
            retrievedChunks: [],
            triggerPath: .autoDetect,
            source: .systemAudio,
            speaker: .interviewer,
            preserveFallbackSayFirst: false
        )

        let visible = try #require(appState.currentSuggestion)
        #expect(visible.id == currentProviderCard.id)
        #expect(visible.stageBStatus == "completed")
        #expect(visible.sayFirstSource == "deepseek_stream")
        #expect(visible.finalVisibleSource == "deepseek_stream")
        #expect(visible.sayFirst == currentProviderCard.sayFirst)
    }

    @Test
    func completedProviderFirstAnswerIsNotPersistedAsSemanticFallbackWhenStageBExpansionRejected() async throws {
        let (appState, session, _, _) = try makeAppState(client: ConsecutiveQuestionLLMClient(), bindCandidateContext: true)
        let question = try makeQuestion(
            sessionID: session.id,
            text: "How did the robot turn noisy camera input into a confident decision about which object to approach?",
            suffix: "provider-first-answer-stage-b-rejected"
        )
        try appState.suggestionRepository.saveDetectedQuestion(question)
        let generationID = "generation-provider-first-answer-stage-b-rejected"
        appState.activateGeneration(
            question: question,
            generationID: generationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        appState.lastDetectedQuestion = question

        let providerSayFirst = "I inspected logs to isolate noisy camera input, then calibrated the camera and IMU, filtered unstable YOLOv8 detections, fused them with depth-based localization, and tested that perception confidence was stable before navigation and grasp planning."
        var currentProviderCard = SuggestionCard(
            id: "current-provider-completed-first-answer",
            sessionID: session.id,
            questionID: question.id,
            strategy: "DeepSeek",
            sayFirst: providerSayFirst,
            keyPoints: [
                "Calibrated camera and IMU to reduce noise.",
                "Filtered unstable YOLOv8 detections.",
                "Used stable perception confidence before navigation and grasp planning."
            ],
            followUpReady: [],
            confidence: 0.86,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .medium,
            modelName: "deepseek-v4-flash",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )
        currentProviderCard.questionText = question.questionText
        currentProviderCard.promptPrimaryQuestion = question.questionText
        currentProviderCard.generationID = generationID
        currentProviderCard.sayFirstSource = "deepseek_stream"
        currentProviderCard.finalVisibleSource = "deepseek_stream"
        currentProviderCard.isLocal = false
        currentProviderCard.softFallbackUsed = false
        currentProviderCard.stageBCompleted = false
        currentProviderCard.stageBStatus = "expanding"
        appState.currentSuggestion = currentProviderCard

        let plan = StageBApplicationPlan(
            generationID: generationID,
            detectedQuestionID: question.id,
            action: .useSemanticFallback,
            fallbackReason: "Rejected incomplete full-card expansion: missing terminal punctuation.",
            shouldPersist: true,
            shouldUpdateVisibleCard: true,
            safeDiagnostics: [
                "providerStatus": GenerationProviderStatus.completed.rawValue,
                "stageBClassification": StageBResultClassification.fallbackRequired.rawValue
            ],
            identity: GenerationIdentity(question: question, generationID: generationID, contextSnapshotID: session.contextSnapshotID)
        )
        let rejectedSections = StreamingSuggestionSections(
            strategy: "DeepSeek",
            sayFirst: "I would explain the pipeline",
            keyPoints: [],
            followUpReady: [],
            caution: ""
        )

        try await appState.applyStageBApplicationPlan(
            plan,
            sections: rejectedSections,
            cardID: "local-semantic-fallback-should-not-win",
            generationID: generationID,
            question: question,
            session: session,
            requestStart: Date(),
            stageBStreamStartedMS: nil,
            retrievedChunks: [],
            triggerPath: .autoDetect,
            source: .systemAudio,
            speaker: .interviewer,
            preserveFallbackSayFirst: false
        )

        let visible = try #require(appState.currentSuggestion)
        #expect(visible.id == currentProviderCard.id)
        #expect(visible.stageBStatus == "completed")
        #expect(visible.stageBCompleted == true)
        #expect(visible.finalVisibleSource == "deepseek_stream")
        #expect(visible.sayFirstSource == "deepseek_stream")
        #expect(visible.isLocal == false)
        #expect(visible.softFallbackUsed == false)
        #expect(visible.sayFirst == providerSayFirst)
        try await waitUntil(timeout: 3.0) {
            ((try? appState.suggestionRepository.suggestions(sessionID: session.id)
                .filter { $0.questionText == question.questionText }
                .count) ?? 0) == 1
        }
        let rows = try appState.suggestionRepository.suggestions(sessionID: session.id)
            .filter { $0.questionText == question.questionText }
        #expect(rows.count == 1)
        #expect(rows.first?.finalVisibleSource == "deepseek_stream")
        #expect(rows.first?.isLocal == false)
        #expect(rows.first?.softFallbackUsed == false)
        #expect(rows.first?.stageBStatus == "completed")
        #expect(rows.first?.stageBCompleted == true)
    }

    @Test
    func providerStageBSuccessDerivesProviderOwnedKeyPointsWhenSectionMissing() async throws {
        let (appState, session, _, _) = try makeAppState(client: ConsecutiveQuestionLLMClient(), bindCandidateContext: true)
        let question = try makeQuestion(
            sessionID: session.id,
            text: "How did the robot turn noisy camera input into a confident decision about which object to approach?",
            suffix: "provider-empty-keypoints"
        )
        try appState.suggestionRepository.saveDetectedQuestion(question)
        let generationID = "generation-provider-empty-keypoints"
        appState.activateGeneration(
            question: question,
            generationID: generationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        appState.lastDetectedQuestion = question
        appState.activeRealtimeProvider = nil

        let providerSayFirst = "I inspected logs to isolate noisy camera data, then calibrated the sensors and built a robust YOLOv8 perception pipeline that filtered sensor noise; I tested it under varying lighting and occlusion to validate stable object-approach decisions."
        var currentProviderCard = SuggestionCard(
            id: "current-provider-empty-keypoints",
            sessionID: session.id,
            questionID: question.id,
            strategy: "DeepSeek",
            sayFirst: providerSayFirst,
            keyPoints: [],
            followUpReady: [],
            confidence: 0.85,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .medium,
            modelName: "deepseek-v4-flash",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )
        currentProviderCard.questionText = question.questionText
        currentProviderCard.promptPrimaryQuestion = question.questionText
        currentProviderCard.generationID = generationID
        currentProviderCard.sayFirstSource = "deepseek_stream"
        currentProviderCard.finalVisibleSource = "deepseek_stream"
        currentProviderCard.isLocal = false
        appState.currentSuggestion = currentProviderCard

        let plan = StageBApplicationPlan(
            generationID: generationID,
            detectedQuestionID: question.id,
            action: .applyFullCard,
            fallbackReason: nil,
            shouldPersist: true,
            shouldUpdateVisibleCard: true,
            safeDiagnostics: [:],
            identity: GenerationIdentity(question: question, generationID: generationID, contextSnapshotID: session.contextSnapshotID)
        )
        let sections = StreamingSuggestionSections(
            strategy: "DeepSeek",
            sayFirst: providerSayFirst,
            keyPoints: [],
            followUpReady: [],
            caution: ""
        )

        try await appState.applyStageBApplicationPlan(
            plan,
            sections: sections,
            cardID: "provider-empty-keypoints-card",
            generationID: generationID,
            question: question,
            session: session,
            requestStart: Date(),
            stageBStreamStartedMS: nil,
            retrievedChunks: [],
            triggerPath: .autoDetect,
            source: .systemAudio,
            speaker: .interviewer,
            preserveFallbackSayFirst: false
        )

        let visible = try #require(appState.currentSuggestion)
        #expect(visible.stageBStatus == "completed")
        #expect(visible.finalVisibleSource == "deepseek_stream")
        #expect(visible.sayFirstSource == "deepseek_stream")
        #expect(visible.isLocal == false)
        #expect(visible.softFallbackUsed == false)
        #expect(visible.keyPoints.isEmpty == false)
        #expect(visible.keyPoints.joined(separator: " ").localizedCaseInsensitiveContains("YOLOv8") ||
            visible.keyPoints.joined(separator: " ").localizedCaseInsensitiveContains("sensor noise"))
    }

    @Test
    func substantiveProviderFirstAnswerMissingOnlyPeriodDoesNotBecomeTimeoutFallback() async throws {
        let (appState, session, _, _) = try makeAppState(client: ConsecutiveQuestionLLMClient(), bindCandidateContext: true)
        let question = try makeQuestion(
            sessionID: session.id,
            text: "How did the robot turn noisy camera input into a confident decision about which object to approach?",
            suffix: "provider-timeout-period"
        )
        try appState.suggestionRepository.saveDetectedQuestion(question)
        let generationID = "provider-timeout-period-generation"
        let requestStart = Date()
        appState.activateGeneration(
            question: question,
            generationID: generationID,
            triggerPath: .autoDetect,
            requestStart: requestStart,
            source: .systemAudio,
            speaker: .interviewer
        )

        var card = SuggestionCard(
            id: "provider-timeout-period-card",
            sessionID: session.id,
            questionID: question.id,
            strategy: "DeepSeek First Answer",
            sayFirst: "I inspected logs to isolate sensor noise and perception drift, then used a ROS2 pipeline with YOLOv8 detection, vision-guided localization, and camera-IMU calibration; I tested it in cluttered environments to validate stable object-approach decisions",
            keyPoints: [],
            followUpReady: [],
            confidence: 0.9,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .low,
            modelName: "deepseek-v4-flash",
            promptVersion: "test",
            providerKind: .deepSeek,
            providerName: "DeepSeek",
            providerBaseURL: "https://api.deepseek.com",
            latencyMS: 2_700,
            isLocal: false,
            rawJSON: nil,
            createdAt: Date(),
            sayFirstSource: "deepseek_stream_timeout"
        )
        card.questionText = question.questionText
        card.promptQuestionText = question.questionText
        card.promptPrimaryQuestion = question.questionText
        card.generationID = generationID
        card.finalVisibleSource = "deepseek_stream_timeout"
        card.softFallbackUsed = true
        card.stageBCompleted = false
        card.stageBStatus = "timed_out"
        card.deepseekFirstTokenMS = 2_600
        card.deepseekFirstVisibleMS = 2_700
        appState.currentSuggestion = card

        let finished = appState.finishGenerationWithVisibleCard(
            card,
            generationID: generationID,
            question: question,
            session: session,
            requestStart: requestStart,
            retrievedChunks: [],
            triggerPath: .autoDetect,
            timedOut: true
        )

        #expect(finished)
        let visible = try #require(appState.currentSuggestion)
        #expect(visible.sayFirst.hasSuffix("."))
        #expect(visible.finalVisibleSource == "deepseek_stream")
        #expect(visible.sayFirstSource == "deepseek_stream")
        #expect(visible.providerName == "DeepSeek")
        #expect(visible.modelName == "deepseek-v4-flash")
        #expect(visible.isLocal == false)
        #expect(visible.softFallbackUsed == false)
        #expect(visible.stageBCompleted == true)
        #expect(visible.stageBStatus == "completed")
        #expect(visible.keyPoints.isEmpty == false)
        #expect(visible.alignmentVerdict == .aligned)

        try await waitUntil(timeout: 5.0) {
            guard let persisted = try? appState.suggestionRepository.suggestions(sessionID: session.id).first(where: { $0.id == card.id }) else {
                return false
            }
            return persisted.finalVisibleSource == "deepseek_stream" &&
                persisted.sayFirstSource == "deepseek_stream" &&
                persisted.isLocal == false &&
                persisted.softFallbackUsed == false &&
                persisted.stageBCompleted == true &&
                persisted.keyPoints.isEmpty == false
        }
    }

    @Test
    func lateFirstProviderCardCannotOverwriteSecondCurrentCard() async throws {
        let (appState, session, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let traceURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("stale-provider-\(UUID().uuidString).jsonl")
        appState.runtimeTranscriptTraceLogURL = traceURL
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "Why do you want this role?",
            suffix: "late-provider-second"
        )
        let secondGenerationID = "late-provider-generation-2"
        appState.activateGeneration(
            question: secondQuestion,
            generationID: secondGenerationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        var secondCard = SuggestionCard(
            id: "late-provider-card-2",
            sessionID: session.id,
            questionID: secondQuestion.id,
            strategy: "Role fit",
            sayFirst: "I want this role because it connects my robotics and deployed AI experience.",
            keyPoints: ["Robotics fit"],
            followUpReady: [],
            confidence: 0.9,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .low,
            modelName: "test",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )
        secondCard.questionText = secondQuestion.questionText
        secondCard.promptPrimaryQuestion = secondQuestion.questionText
        secondCard.generationID = secondGenerationID
        appState.currentSuggestion = secondCard

        var staleFirstCard = secondCard
        staleFirstCard.id = "late-provider-card-1"
        staleFirstCard.questionID = firstQuestion.id
        staleFirstCard.questionText = firstQuestion.questionText
        staleFirstCard.promptQuestionText = firstQuestion.questionText
        staleFirstCard.promptPrimaryQuestion = firstQuestion.questionText
        staleFirstCard.generationID = "late-provider-generation-1"
        staleFirstCard.sayFirst = "I can explain my first project, but this answer belongs to Q1."

        let applied = appState.displaySuggestionIfAligned(
            staleFirstCard,
            question: firstQuestion,
            generationID: "late-provider-generation-1",
            triggerPath: .autoDetect
        )

        #expect(applied == false)
        #expect(appState.currentSuggestion?.id == secondCard.id)
        #expect(appState.currentSuggestion?.questionText == secondQuestion.questionText)
        try await waitForTraceEvent("currentCardRegressionRejected", at: traceURL)
        let trace = try String(contentsOf: traceURL, encoding: .utf8)
        #expect(trace.contains("\"event_type\":\"staleGenerationResultRejected\""))
        #expect(trace.contains("\"event_type\":\"currentCardRegressionRejected\""))
        #expect(trace.contains("late-provider-generation-1"))
        #expect(trace.contains(secondGenerationID))
        #expect(trace.contains("\"old_accepted_question_id\":\"\(firstQuestion.id)\""))
        #expect(trace.contains("\"current_accepted_question_id\":\"\(secondQuestion.id)\""))
        #expect(trace.contains("\"source_callback\":\"provider_display\""))
    }

    @Test
    func visibleQuestionTextStaysBoundToVisibleCardWhileNewQuestionIsQueued() throws {
        let (appState, session, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "Why did diffusion outperform autoregressive and flow-matching decoders?",
            suffix: "queued-visible-binding"
        )
        var firstCard = SuggestionCard(
            id: "visible-first-card",
            sessionID: session.id,
            questionID: firstQuestion.id,
            strategy: "Project walkthrough",
            sayFirst: "I can explain the first project clearly.",
            keyPoints: [],
            followUpReady: [],
            confidence: 0.9,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .low,
            modelName: "test",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )
        firstCard.questionText = firstQuestion.questionText
        firstCard.promptPrimaryQuestion = firstQuestion.questionText
        appState.currentSuggestion = firstCard
        appState.lastDetectedQuestion = secondQuestion
        appState.possibleQuestion = secondQuestion

        #expect(appState.visibleQuestionText(for: appState.currentSuggestion) == firstQuestion.questionText)
    }

    @Test
    func streamedAnswerQuestionUsesActiveGenerationSnapshot() throws {
        let (appState, session, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "How did you convert DROID demonstrations for MuJoCo Franka?",
            suffix: "queued-stream-label"
        )
        appState.activateGeneration(
            question: firstQuestion,
            generationID: "stream-owner-generation",
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        appState.streamedSayFirst = "I built the LeoRover project with ROS2 navigation and YOLOv8 perception."
        appState.currentSuggestion = nil
        appState.lastDetectedQuestion = secondQuestion
        appState.possibleQuestion = secondQuestion

        #expect(appState.visibleQuestionText(for: nil) == firstQuestion.questionText)
        let snapshot = try #require(appState.visibleSuggestionState)
        #expect(snapshot.identity.acceptedQuestionID == firstQuestion.id)
        #expect(snapshot.questionText == firstQuestion.questionText)
        #expect(snapshot.answerText == appState.streamedSayFirst)
    }

    @Test
    func loadingQuestionUsesActiveGenerationSnapshotBeforeAnswerTextExists() throws {
        let (appState, session, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let secondQuestion = try makeQuestion(
            sessionID: session.id,
            text: "If YOLOv8 is confidently wrong, how would you debug it?",
            suffix: "loading-label"
        )
        appState.activateGeneration(
            question: firstQuestion,
            generationID: "loading-owner-generation",
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        appState.currentSuggestion = nil
        appState.streamedSayFirst = ""
        appState.lastDetectedQuestion = secondQuestion

        #expect(appState.visibleSuggestionState?.identity.acceptedQuestionID == firstQuestion.id)
        #expect(appState.visibleSuggestionState?.questionText == firstQuestion.questionText)
    }

    @Test
    func terminalGenerationFailureShowsVisibleErrorInsteadOfEmptyAnswer() throws {
        let (appState, _, question, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let generationID = "visible-terminal-failure-generation"
        appState.activateGeneration(
            question: question,
            generationID: generationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        appState.currentSuggestion = nil
        appState.streamedSayFirst = ""

        appState.markGenerationFailed(
            generationID: generationID,
            reason: "provider unavailable",
            providerError: "HTTP 503"
        )

        let visible = try #require(appState.visibleSuggestionState)
        #expect(visible.questionText == question.questionText)
        #expect(visible.answerText.isEmpty)
        #expect(visible.generationErrorText == "Generation failed: provider unavailable")
        #expect(visible.answerText.localizedCaseInsensitiveContains("No answer yet") == false)
        #expect(appState.visibleAssistantRenderState.generationErrorText == "Generation failed: provider unavailable")
        #expect(appState.visibleAssistantRenderState.answerText.isEmpty)
    }

    @Test
    func asrTraceDoesNotInheritActiveGenerationIdentity() async throws {
        let (appState, session, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let traceURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("asr-provenance-\(UUID().uuidString).jsonl")
        appState.runtimeTranscriptTraceLogURL = traceURL
        appState.activateGeneration(
            question: firstQuestion,
            generationID: "active-generation-not-asr-owner",
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        let segment = TranscriptSegment(
            id: "new-asr-callback",
            sessionID: session.id,
            source: .systemAudio,
            speaker: .interviewer,
            text: "How did you adapt DROID demonstrations for MuJoCo?",
            createdAt: Date(),
            asrFinalizationReason: "stable_partial",
            recognitionTaskID: "new-recognition-task",
            recognitionEventSequence: 4,
            sourceTextStartUTF16: 0,
            sourceTextEndUTF16: 49,
            recognitionIsFinal: true
        )

        appState.recordASRTranscriptRuntimeEvent(for: segment)

        try await waitForTraceEvent("asrFinal", at: traceURL)
        let trace = try String(contentsOf: traceURL, encoding: .utf8)
        #expect(trace.contains("\"event_type\":\"asrFinal\""))
        #expect(trace.contains("\"generation_id\":\"\""))
        #expect(!trace.contains("active-generation-not-asr-owner"))
    }

    @Test
    func cancellingActiveStageBDoesNotPersistFinalRow() async throws {
        let (appState, session, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let traceURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("cancelled-persistence-\(UUID().uuidString).jsonl")
        appState.runtimeTranscriptTraceLogURL = traceURL
        let generationID = "cancelled-generation"
        appState.activateGeneration(
            question: firstQuestion,
            generationID: generationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        var card = SuggestionCard(
            id: "cancelled-card",
            sessionID: session.id,
            questionID: firstQuestion.id,
            strategy: "Project walkthrough",
            sayFirst: "I built the LeoRover project with ROS2 navigation, YOLOv8 perception, and real robot reliability checks.",
            keyPoints: ["ROS2 navigation", "YOLOv8 perception"],
            followUpReady: [],
            confidence: 0.9,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .low,
            modelName: "test",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )
        card.detectedQuestionID = firstQuestion.id
        card.questionText = firstQuestion.questionText
        card.promptQuestionText = firstQuestion.questionText
        card.promptPrimaryQuestion = firstQuestion.questionText
        card.generationID = generationID
        card.questionIntent = AnswerRelevancePolicy.intent(for: firstQuestion.questionText)
        card.alignmentVerdict = .aligned
        appState.currentSuggestion = card
        appState.stageBTaskActive = true
        appState.simulatedSuggestionPersistenceDelayNanoseconds = 150_000_000
        appState.persistSuggestionInBackground(
            card,
            chunks: [],
            generationID: generationID,
            requestStart: Date()
        )

        appState.cancelStageBTask()
        try await Task.sleep(nanoseconds: 350_000_000)

        #expect(try appState.suggestionRepository.suggestions(sessionID: session.id).isEmpty)
        let trace = try String(contentsOf: traceURL, encoding: .utf8)
        #expect(trace.contains("\"event_type\":\"cancelledGenerationPersistenceRejected\""))
    }

    @Test
    func duplicateLogicalPersistenceFromSameTranscriptSegmentIsRejected() async throws {
        let (appState, session, firstQuestion, _) = try makeAppState(client: ConsecutiveQuestionLLMClient(), bindCandidateContext: true)
        let traceURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("duplicate-persistence-\(UUID().uuidString).jsonl")
        appState.runtimeTranscriptTraceLogURL = traceURL
        let questionText = firstQuestion.questionText

        func card(id: String, questionID: String, generationID: String) -> SuggestionCard {
            var value = SuggestionCard(
                id: id,
                sessionID: session.id,
                questionID: questionID,
                strategy: "Project walkthrough",
                sayFirst: "I built the LeoRover navigation pipeline with ROS2, perception, planning, and real-robot reliability checks, which improved recovery behaviour.",
                keyPoints: ["ROS2 navigation", "Real robot reliability"],
                followUpReady: [],
                confidence: 0.9,
                caution: nil,
                evidenceUsed: [],
                riskLevel: .low,
                modelName: "test",
                promptVersion: "test",
                rawJSON: nil,
                createdAt: Date()
            )
            value.questionText = questionText
            value.promptQuestionText = questionText
            value.promptPrimaryQuestion = questionText
            value.transcriptSegmentID = "same-cumulative-segment"
            value.generationID = generationID
            value.questionIntent = AnswerRelevancePolicy.intent(for: questionText)
            value.alignmentVerdict = .aligned
            value.stageBCompleted = true
            return value
        }

        let firstGenerationID = "duplicate-persistence-generation-1"
        appState.activateGeneration(
            question: firstQuestion,
            generationID: firstGenerationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        let firstCard = card(id: "duplicate-card-1", questionID: firstQuestion.id, generationID: firstGenerationID)
        appState.persistSuggestionInBackground(
            firstCard,
            chunks: [],
            generationID: firstGenerationID,
            requestStart: Date()
        )
        try await waitUntil(timeout: 8.0) {
            (try? appState.suggestionRepository.suggestions(sessionID: session.id).count) == 1
        }

        let repeatedQuestion = DetectedQuestion(
            id: "duplicate-question-2",
            sessionID: session.id,
            transcriptSegmentID: nil,
            questionText: questionText,
            intent: firstQuestion.intent,
            answerStrategy: firstQuestion.answerStrategy,
            confidence: 0.95,
            reason: "Cumulative replay",
            shouldTrigger: true,
            questionComplete: true,
            modelName: "test",
            promptVersion: "test",
            createdAt: Date()
        )
        try appState.suggestionRepository.saveDetectedQuestion(repeatedQuestion)
        let secondGenerationID = "duplicate-persistence-generation-2"
        appState.activateGeneration(
            question: repeatedQuestion,
            generationID: secondGenerationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        appState.persistSuggestionInBackground(
            card(id: "duplicate-card-2", questionID: repeatedQuestion.id, generationID: secondGenerationID),
            chunks: [],
            generationID: secondGenerationID,
            requestStart: Date()
        )
        try await Task.sleep(nanoseconds: 200_000_000)

        #expect(try appState.suggestionRepository.suggestions(sessionID: session.id).count == 1)
        let trace = try String(contentsOf: traceURL, encoding: .utf8)
        #expect(trace.contains("\"event_type\":\"duplicatePersistenceRejected\""))
        #expect(trace.contains("duplicate-persistence-generation-2"))
    }

    @Test
    func activeGenerationFallbackCarriesCurrentQuestionSnapshot() throws {
        let (appState, session, _, _) = try makeAppState(client: ConsecutiveQuestionLLMClient(), bindCandidateContext: true)
        let thirdQuestion = try makeQuestion(
            sessionID: session.id,
            text: "What was the biggest technical trade-off you made in your robotics projects?",
            suffix: "fallback-third"
        )
        let generationID = "generation-fallback-third"
        appState.activateGeneration(
            question: thirdQuestion,
            generationID: generationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )
        appState.lastDetectedQuestion = thirdQuestion

        #expect(appState.showImmediateFallbackForActiveGenerationIfNeeded(reason: "test-timeout"))
        let visible = try #require(appState.currentSuggestion)
        #expect(visible.detectedQuestionID == thirdQuestion.id)
        #expect(visible.questionText == thirdQuestion.questionText)
        #expect(visible.promptPrimaryQuestion == thirdQuestion.questionText)
        #expect(visible.generationID == generationID)
        #expect(visible.sayFirst.localizedCaseInsensitiveContains("balanced"))
        #expect(visible.sayFirst.localizedCaseInsensitiveContains("latency"))
    }

    @Test
    func terminalGenerationIgnoresLateStreamingStateUpdate() throws {
        let (appState, _, question, _) = try makeAppState(client: ConsecutiveQuestionLLMClient())
        let generationID = "terminal-late-streaming-update"
        appState.activateGeneration(
            question: question,
            generationID: generationID,
            triggerPath: .autoDetect,
            requestStart: Date(),
            source: .systemAudio,
            speaker: .interviewer
        )

        appState.setGenerationUIState(
            .answerReady(questionID: question.id, generationID: generationID, triggerPath: .autoDetect),
            generationID: generationID
        )
        appState.setGenerationUIState(
            .streamingAnswer(questionID: question.id, generationID: generationID, triggerPath: .autoDetect),
            generationID: generationID
        )

        #expect(appState.generationUIState.displayName == "Answer ready")
        #expect(appState.terminalGenerationIDs.contains(generationID))
        #expect(appState.currentGenerationTelemetry.questionID == question.id)
    }

    @Test
    func rapidThreeQuestionSequenceLeavesOnlyLatestQuestionActive() async throws {
        let client = ConsecutiveQuestionLLMClient()
        client.stageADelayByQuestion = [
            "first project": 1_000_000_000,
            "second project": 1_000_000_000,
            "third project": 1_000_000_000
        ]
        let (appState, session, firstQuestion, delayProvider) = try makeAppState(client: client, bindCandidateContext: true)
        let secondQuestion = try makeQuestion(sessionID: session.id, text: "Could you walk me through your second project, the LeoRover navigation pipeline?", suffix: "second-rapid")
        let thirdQuestion = try makeQuestion(sessionID: session.id, text: "Could you walk me through your third project, the LeoRover navigation pipeline?", suffix: "third-rapid")
        try appState.suggestionRepository.saveDetectedQuestion(secondQuestion)
        try appState.suggestionRepository.saveDetectedQuestion(thirdQuestion)
        delayProvider.sleepDuration = 0
        appState.generationFullCardWatchdogNanoseconds = 400_000_000

        let firstTask = Task {
            try await appState.generateSuggestion(for: firstQuestion, session: session, transcript: firstQuestion.questionText, autoGenerated: true)
        }
        try await waitUntil(timeout: 8.0) { appState.activeQuestionID == firstQuestion.id }

        let secondTask = Task {
            try await appState.generateSuggestion(for: secondQuestion, session: session, transcript: secondQuestion.questionText, autoGenerated: true)
        }
        try await waitUntil(timeout: 8.0) { appState.activeQuestionID == secondQuestion.id }

        let thirdTask = Task {
            try await appState.generateSuggestion(for: thirdQuestion, session: session, transcript: thirdQuestion.questionText, autoGenerated: true)
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
            thirdTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == thirdQuestion.id &&
            appState.currentSuggestion?.questionID == thirdQuestion.id &&
            appState.visibleAnswerExists
        }

        #expect(appState.currentSuggestion?.questionID == thirdQuestion.id)
        #expect(appState.currentGenerationTelemetry.questionID == thirdQuestion.id)
        #expect(appState.cancelledGenerationCount >= 2)
        #expect(!appState.shouldShowBlockingAnswerSpinner)
    }

    private func makeAppState(
        client: any LLMClientProtocol,
        contextRetrievalService: ContextRetrievalService? = nil,
        bindCandidateContext: Bool = false
    ) throws -> (AppState, InterviewSession, DetectedQuestion, MockDelayProvider) {
        let database = try TestSupport.makeTemporaryDatabase(prefix: "GenerationUIStateTests")
        let settingsRepository = SettingsRepository(database: database)
        try settingsRepository.ensureDefaultProviderConfigurations()
        if let deepSeek = try settingsRepository.providerConfigurations().first(where: { $0.kind == .deepSeek }) {
            try settingsRepository.setActiveRealtimeProvider(id: deepSeek.id)
        }

        let router = LLMRouter(settingsRepository: settingsRepository, clients: [.deepSeek: client])
        let appState = AppState(
            database: database,
            llmRouter: router,
            contextRetrievalService: contextRetrievalService
        )
        appState.answerProviderModeOverride = .deepSeekPrimary
        let delayProvider = MockDelayProvider()
        appState.delayProvider = delayProvider

        let session: InterviewSession
        if bindCandidateContext {
            let profileID = "generation-ui-profile-\(UUID().uuidString)"
            let projectStatements = [
                "The synthetic candidate built a LeoRover ROS2 navigation project connecting perception, localization, planning, control, and recovery, which improved system reliability.",
                "The synthetic candidate calibrated camera and IMU inputs, filtered unstable YOLOv8 detections and sensor noise, and used depth-based localization before navigation and grasp planning.",
                "The synthetic candidate tested cluttered real-world environments and balanced perception confidence against response latency, which improved robust object-approach decisions."
            ]
            try appState.interviewContextRepository.saveCandidateProfile(CandidateProfile(
                id: profileID,
                displayName: "Synthetic Generation UI Candidate",
                sourceDocumentIDs: ["generation-ui-document"],
                education: [],
                experience: [],
                projects: projectStatements.enumerated().map { index, statement in
                    ProfileEvidence(
                        id: "generation-ui-evidence-\(index)-\(UUID().uuidString)",
                        statement: statement,
                        sourceDocumentID: "generation-ui-document",
                        sourceChunkID: "generation-ui-chunk-\(index)",
                        sourceSpan: statement,
                        confidence: 1,
                        evidenceType: .project,
                        explicitness: .explicit
                    )
                },
                skills: [],
                publications: [],
                achievements: [],
                declaredGaps: [],
                goals: [],
                generatedSummary: nil,
                version: 1,
                updatedAt: Date()
            ))
            appState.refreshAll()
            appState.selectCandidateProfile(profileID)
            appState.selectInterviewDomain(.roboticsResearch)
            session = try appState.createContextBoundSession(mode: .microphone)
        } else {
            session = try appState.sessionRepository.createSession(mode: .microphone)
        }
        appState.currentSession = session

        let question = DetectedQuestion(
            id: UUID().uuidString,
            sessionID: session.id,
            transcriptSegmentID: nil,
            questionText: "Could you walk me through your first project, the LeoRover navigation pipeline?",
            intent: .projectDeepDive,
            answerStrategy: .projectWalkthrough,
            confidence: 0.95,
            reason: "Test",
            shouldTrigger: true,
            questionComplete: true,
            modelName: "mock",
            promptVersion: "test",
            createdAt: Date()
        )
        try appState.suggestionRepository.saveDetectedQuestion(question)
        return (appState, session, question, delayProvider)
    }

    private func makeQuestion(sessionID: String, text: String, suffix: String) throws -> DetectedQuestion {
        DetectedQuestion(
            id: "question-\(suffix)-\(UUID().uuidString)",
            sessionID: sessionID,
            transcriptSegmentID: nil,
            questionText: text,
            intent: .projectDeepDive,
            answerStrategy: .projectWalkthrough,
            confidence: 0.95,
            reason: "Test",
            shouldTrigger: true,
            questionComplete: true,
            modelName: "mock",
            promptVersion: "test",
            createdAt: Date()
        )
    }

    private func waitUntil(timeout: TimeInterval, predicate: @escaping @MainActor () -> Bool) async throws {
        let start = Date()
        let effectiveTimeout = timeout
        while !predicate() {
            if Date().timeIntervalSince(start) > effectiveTimeout {
                throw NSError(
                    domain: "GenerationUIStateTests",
                    code: 1,
                    userInfo: [NSLocalizedDescriptionKey: "Timed out waiting for generation UI state."]
                )
            }
            try await Task.sleep(nanoseconds: 50_000_000)
        }
    }

    private func waitForTraceEvent(
        _ eventType: String,
        at traceURL: URL,
        timeout: TimeInterval = 2.0
    ) async throws {
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            let trace = (try? String(contentsOf: traceURL, encoding: .utf8)) ?? ""
            if trace.contains("\"event_type\":\"\(eventType)\"") {
                return
            }
            try await Task.sleep(nanoseconds: 20_000_000)
        }
        throw NSError(
            domain: "GenerationUIStateTests",
            code: 2,
            userInfo: [NSLocalizedDescriptionKey: "Timed out waiting for trace event \(eventType)."]
        )
    }
}

private final class DeterministicGenerationLLMClient: LLMClientProtocol {
    let providerKind: LLMProviderKind = .deepSeek
    var fullCardContent = """
    {
      "strategy": "Project Walkthrough",
      "say_first": "I can explain the LeoRover project by describing the autonomous object retrieval goal, the ROS2 and YOLOv8 perception pipeline, navigation and manipulation choices, and the real robot result.",
      "key_points": ["LeoRover object retrieval goal", "ROS2 and YOLOv8 perception pipeline", "Navigation, manipulation, and real robot learning"],
      "follow_up_ready": ["I can explain the ROS2 navigation tradeoffs if useful."],
      "confidence": 0.8,
      "caution": "None",
      "evidence_used": [],
      "risk_level": "low"
    }
    """
    var fullCardDelayNS: UInt64 = 0
    var stageBStreamNeverFinishes = false

    func testConnection(configuration: LLMProviderConfiguration) async throws -> LLMConnectionTestResult {
        LLMConnectionTestResult(success: true, message: "Mock OK", latencyMS: 0, models: [])
    }

    func chatCompletion(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) async throws -> LLMChatResult {
        if fullCardDelayNS > 0 {
            try await Task.sleep(nanoseconds: fullCardDelayNS)
        }
        return LLMChatResult(
            content: fullCardContent,
            modelName: "mock-model",
            providerKind: .deepSeek,
            providerName: "DeepSeek",
            baseURL: "",
            latencyMS: 100,
            isLocal: false,
            rawResponse: fullCardContent
        )
    }

    func chatCompletionStream(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) -> AsyncThrowingStream<String, Error> {
        let promptText = messages.map(\.content).joined(separator: "\n")
        let isStageBSectionStream = promptText.contains("Return plain text sections only")
        let hangsStageBStream = stageBStreamNeverFinishes
        return AsyncThrowingStream { continuation in
            Task {
                if isStageBSectionStream {
                    if hangsStageBStream {
                        try? await Task.sleep(nanoseconds: 60_000_000_000)
                    }
                    continuation.finish()
                    return
                }
                for token in ["I ", "built ", "a ", "LeoRover ", "robotics ", "project ", "with ", "ROS2 ", "perception ", "and ", "navigation."] {
                    continuation.yield(token)
                }
                continuation.finish()
            }
        }
    }

    func listModels(configuration: LLMProviderConfiguration) async throws -> [LLMModelInfo] {
        []
    }
}

private final class ConsecutiveQuestionLLMClient: LLMClientProtocol, @unchecked Sendable {
    let providerKind: LLMProviderKind = .deepSeek
    var stageADelayByQuestion = [String: UInt64]()
    var stageBDelayByQuestion = [String: UInt64]()
    var hangingStageAQuestions = Set<String>()

    func testConnection(configuration: LLMProviderConfiguration) async throws -> LLMConnectionTestResult {
        LLMConnectionTestResult(success: true, message: "Mock OK", latencyMS: 0, models: [])
    }

    func chatCompletion(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) async throws -> LLMChatResult {
        let questionKey = questionKey(from: messages)
        if let delay = stageBDelayByQuestion[questionKey] {
            try? await Task.sleep(nanoseconds: delay)
        }
        let content = fullCardJSON(for: questionKey)
        return LLMChatResult(
            content: content,
            modelName: "mock-model",
            providerKind: .deepSeek,
            providerName: "DeepSeek",
            baseURL: "",
            latencyMS: 100,
            isLocal: false,
            rawResponse: content
        )
    }

    func chatCompletionStream(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) -> AsyncThrowingStream<String, Error> {
        let promptText = messages.map(\.content).joined(separator: "\n")
        let questionKey = questionKey(from: messages)
        let isStageB = promptText.contains("Return plain text sections only")
        let stageADelay = stageADelayByQuestion[questionKey] ?? 0
        let stageBDelay = stageBDelayByQuestion[questionKey] ?? 0
        let hangs = hangingStageAQuestions.contains(questionKey) && !isStageB

        return AsyncThrowingStream { continuation in
            let task = Task {
                if hangs {
                    try? await Task.sleep(nanoseconds: 60_000_000_000)
                    continuation.finish()
                    return
                }
                if isStageB {
                    if stageBDelay > 0 {
                        try? await Task.sleep(nanoseconds: stageBDelay)
                    }
                    for token in stageBSections(for: questionKey) {
                        if Task.isCancelled {
                            continuation.finish()
                            return
                        }
                        continuation.yield(token)
                    }
                    continuation.finish()
                    return
                }
                if stageADelay > 0 {
                    try? await Task.sleep(nanoseconds: stageADelay)
                }
                for token in ["I ", "can ", "walk ", "through ", "my ", "\(questionKey) ", "clearly."] {
                    if Task.isCancelled {
                        continuation.finish()
                        return
                    }
                    continuation.yield(token)
                }
                continuation.finish()
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    func listModels(configuration: LLMProviderConfiguration) async throws -> [LLMModelInfo] {
        []
    }

    private func questionKey(from messages: [LLMChatMessage]) -> String {
        let promptText = messages.map(\.content).joined(separator: "\n").lowercased()
        if promptText.contains("third project") {
            return "third project"
        }
        if promptText.contains("second project") {
            return "second project"
        }
        return "first project"
    }

    private func fullCardJSON(for questionKey: String) -> String {
        """
        {
          "strategy": "Project Walkthrough",
          "say_first": "I can explain my \(questionKey) in the LeoRover work by covering the autonomous object retrieval goal, ROS2 and YOLOv8 perception, navigation, manipulation, and the real robot result.",
          "key_points": ["LeoRover goal for \(questionKey)", "ROS2, YOLOv8, navigation, and manipulation", "Real robot result and learning"],
          "follow_up_ready": ["I can go deeper on robotics tradeoffs if helpful."],
          "confidence": 0.82,
          "caution": "None",
          "evidence_used": [],
          "risk_level": "low"
        }
        """
    }

    private func stageBSections(for questionKey: String) -> [String] {
        [
            "Strategy: Project Walkthrough\n",
            "Say First: I can explain my \(questionKey) in the LeoRover work by covering the autonomous object retrieval goal, ROS2 and YOLOv8 perception, navigation, manipulation, and the real robot result.\n",
            "Key Points:\n",
            "- LeoRover goal for \(questionKey)\n",
            "- ROS2, YOLOv8, navigation, and manipulation\n",
            "- Real robot result and learning\n",
            "Follow-up Ready:\n",
            "- I can go deeper on tradeoffs if helpful.\n",
            "Caution: None\n"
        ]
    }
}

private final class SlowGenerationContextRetrievalService: ContextRetrievalService {
    let delayNanoseconds: UInt64

    init(delayNanoseconds: UInt64) {
        self.delayNanoseconds = delayNanoseconds
    }

    func retrieveContextWithTrace(
        question: String,
        intent: QuestionIntent,
        maxCVWords: Int,
        maxJDWords: Int,
        strategy: AnswerStrategy?
    ) async throws -> (context: RetrievedContext, trace: RetrievalTrace) {
        try await Task.sleep(nanoseconds: delayNanoseconds)
        let context = RetrievedContext(cvChunks: [], jobDescriptionChunks: [])
        let trace = RetrievalTrace(
            id: UUID(),
            query: question,
            intent: intent.rawValue,
            createdAt: Date(),
            rankedCVChunks: [],
            rankedJDChunks: [],
            includedCVChunks: [],
            includedJDChunks: [],
            excludedCVChunks: [],
            excludedJDChunks: [],
            cvWordsUsed: 0,
            jdWordsUsed: 0,
            cvWordBudget: maxCVWords,
            jdWordBudget: maxJDWords,
            retrievalLatencyMS: Double(delayNanoseconds) / 1_000_000.0,
            emptyQueryFallbackUsed: false,
            zeroScoreFallbackUsed: false
        )
        return (context, trace)
    }
}
