import Foundation
import GRDB
import Testing
@testable import InterviewCopilotMac

@Suite(.serialized)
@MainActor
struct QuestionAnswerAlignmentTests {
    @Test
    func oneQuestionOneAnswerBindsSuggestionToDetectedQuestion() async throws {
        let client = AlignmentLLMClient()
        let (appState, database, session) = try makeAppState(client: client)
        let question = try saveQuestion(
            "Why do you want to join our team?",
            sessionID: session.id,
            repository: appState.suggestionRepository,
            suffix: "role"
        )

        appState.setActiveQuestionForTesting(question)
        var alignedCard = SuggestionCard(
            id: "one-question-card",
            sessionID: session.id,
            questionID: question.id,
            strategy: "Role motivation",
            sayFirst: "I want to join because this role connects with my robotics and AI experience.",
            keyPoints: ["Robotics and AI fit", "Engineering growth"],
            followUpReady: [],
            confidence: 0.9,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .low,
            modelName: "alignment-test",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )
        alignedCard.questionText = question.questionText
        alignedCard.generationID = "generation-one-question"
        alignedCard.triggerPath = .autoDetect

        let accepted = appState.applySuggestionIfAlignedForTesting(
            alignedCard,
            question: question,
            generationID: alignedCard.generationID
        )
        #expect(accepted)

        let card = try #require(appState.currentSuggestion)
        #expect(card.detectedQuestionID == question.id)
        #expect(card.questionText == question.questionText)
        #expect(card.generationID == "generation-one-question")
        #expect(card.triggerPath == .autoDetect)
        #expect(card.sayFirst.localizedCaseInsensitiveContains("robotics"))

        try appState.suggestionRepository.saveSuggestionCard(card)
        let stored = try suggestionAlignmentRows(database: database)
        let storedCard = try #require(stored.first)
        #expect(stored.count == 1)
        #expect(storedCard.detectedQuestionID == question.id)
        #expect(storedCard.detectedQuestionID == storedCard.joinedQuestionID)
        #expect(storedCard.suggestionQuestion == question.questionText)
    }

    @Test
    func twoConsecutiveQuestionsKeepLateFirstAnswerOutOfSecondUI() async throws {
        let client = AlignmentLLMClient()
        client.stageBDelayByQuestionKeyword = ["about yourself": 500_000_000]
        let (appState, database, session) = try makeAppState(client: client)
        appState.delayProvider = MockDelayProvider()
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000

        let first = try saveQuestion("Could you tell me about yourself?", sessionID: session.id, repository: appState.suggestionRepository, suffix: "self")
        let second = try saveQuestion("What was the hardest technical challenge in your LeoRover project?", sessionID: session.id, repository: appState.suggestionRepository, suffix: "challenge")

        let firstTask = Task {
            try await appState.generateSuggestion(for: first, session: session, transcript: first.questionText, autoGenerated: true)
        }
        try await waitUntil(timeout: 8.0) {
            appState.currentSuggestion?.detectedQuestionID == first.id &&
            appState.stageBTaskActive
        }

        let secondTask = Task {
            try await appState.generateSuggestion(for: second, session: session, transcript: second.questionText, autoGenerated: true)
        }
        defer {
            firstTask.cancel()
            secondTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.currentSuggestion?.detectedQuestionID == second.id &&
            appState.currentQABinding.bindingStatus == .matched
        }
        try await Task.sleep(nanoseconds: 700_000_000)

        let visible = try #require(appState.currentSuggestion)
        #expect(visible.detectedQuestionID == second.id)
        #expect(visible.questionText == second.questionText)
        #expect(!visible.sayFirst.localizedCaseInsensitiveContains("MSc Robotics"))
        #expect(!visible.sayFirst.localizedCaseInsensitiveContains("University of Manchester"))
        #expect(appState.staleAnswerDiscardCount >= 1 || appState.cancelledGenerationCount >= 1)

        try await waitUntil(timeout: 8.0) {
            guard let rows = try? suggestionAlignmentRows(database: database) else { return false }
            return rows.contains { $0.detectedQuestionID == first.id && $0.suggestionQuestion == first.questionText } &&
                rows.contains { $0.detectedQuestionID == second.id && $0.suggestionQuestion == second.questionText }
        }
        let rows = try suggestionAlignmentRows(database: database)
        #expect(rows.allSatisfy { $0.detectedQuestionID == $0.joinedQuestionID })
        #expect(rows.contains { $0.detectedQuestionID == first.id && $0.suggestionQuestion == first.questionText })
        #expect(rows.contains { $0.detectedQuestionID == second.id && $0.suggestionQuestion == second.questionText })
    }

    @Test
    func rapidThreeQuestionSequenceLeavesOnlyLatestQuestionBoundToUI() async throws {
        let client = AlignmentLLMClient()
        client.stageADelayByQuestionKeyword = [
            "about yourself": 700_000_000,
            "LeoRover": 700_000_000
        ]
        let (appState, _, session) = try makeAppState(client: client)
        appState.delayProvider = MockDelayProvider()
        appState.generationFullCardWatchdogNanoseconds = 800_000_000

        let first = try saveQuestion("Tell me about yourself", sessionID: session.id, repository: appState.suggestionRepository, suffix: "self")
        let second = try saveQuestion("Walk me through your LeoRover project", sessionID: session.id, repository: appState.suggestionRepository, suffix: "project")
        let third = try saveQuestion("Why do you want this role?", sessionID: session.id, repository: appState.suggestionRepository, suffix: "role")

        let firstTask = Task { try await appState.generateSuggestion(for: first, session: session, transcript: first.questionText, autoGenerated: true) }
        try await waitUntil(timeout: 8.0) { appState.activeQuestionID == first.id }
        let secondTask = Task { try await appState.generateSuggestion(for: second, session: session, transcript: second.questionText, autoGenerated: true) }
        try await waitUntil(timeout: 8.0) { appState.activeQuestionID == second.id }
        let thirdTask = Task { try await appState.generateSuggestion(for: third, session: session, transcript: third.questionText, autoGenerated: true) }
        defer {
            firstTask.cancel()
            secondTask.cancel()
            thirdTask.cancel()
        }

        try await waitUntil(timeout: 8.0) {
            appState.activeQuestionID == third.id &&
            appState.currentSuggestion?.detectedQuestionID == third.id &&
            appState.currentQABinding.bindingStatus == .matched
        }

        #expect(appState.currentSuggestion?.questionText == third.questionText)
        #expect(appState.currentSuggestion?.sayFirst.localizedCaseInsensitiveContains("MSc Robotics") != true)
        #expect(appState.currentSuggestion?.sayFirst.localizedCaseInsensitiveContains("LeoRover") != true)
        #expect(appState.answerQuestionMismatchCount == 0)
    }

    @Test
    func longTranscriptMultiQuestionExtractionBindsLatestSuggestionToLatestQuestion() async throws {
        let client = AlignmentLLMClient()
        let (appState, database, session) = try makeAppState(client: client)
        var settings = appState.settings
        settings.audioCaptureMode = .systemAudioOnly
        settings.automaticQuestionDetectionEnabled = true
        appState.saveSettings(settings)
        appState.currentCaptureRuntimeState = .listening
        appState.liveState = .listening
        appState.generationFullCardWatchdogNanoseconds = 20_000_000_000

        await appState.handleTranscriptSegment(TranscriptSegment(
            id: "alignment-long-transcript",
            sessionID: session.id,
            source: .systemAudio,
            speaker: .interviewer,
            text: Self.longQuestionOnlyTranscript,
            createdAt: Date(),
            confidence: 1.0
        ))

        try await waitUntil(timeout: 30.0) {
            appState.detectedQuestionsInSessionCount == 9 &&
            appState.currentSuggestion?.detectedQuestionID == appState.lastDetectedQuestion?.id &&
            appState.currentQABinding.bindingStatus == .matched
        }

        let latestQuestion = try #require(appState.lastDetectedQuestion)
        let card = try #require(appState.currentSuggestion)
        #expect(card.detectedQuestionID == latestQuestion.id)
        #expect(card.questionText == latestQuestion.questionText)
        #expect(card.questionText?.localizedCaseInsensitiveContains("do you have any questions for us") == true)

        try await waitUntil(timeout: 8.0) {
            (try? suggestionAlignmentRows(database: database).isEmpty == false) == true
        }
        let rows = try suggestionAlignmentRows(database: database)
        #expect(rows.allSatisfy { $0.detectedQuestionID == $0.joinedQuestionID })
        #expect(rows.allSatisfy { $0.suggestionQuestion == $0.detectedQuestion })
    }

    @Test
    func dbRoundtripPersistsDetectedQuestionBindingAndQuestionSnapshot() throws {
        let database = try TestSupport.makeTemporaryDatabase(prefix: "QuestionAnswerAlignmentDB")
        let sessions = SessionRepository(database: database)
        let suggestions = SuggestionRepository(database: database)
        let session = try sessions.createSession(mode: .mock, title: "Alignment DB")
        let question = try saveQuestion(
            "How did you handle noisy detections or localisation errors?",
            sessionID: session.id,
            repository: suggestions,
            suffix: "noise"
        )
        let card = SuggestionCard(
            id: "alignment-card",
            sessionID: session.id,
            questionID: question.id,
            strategy: "Technical explanation",
            sayFirst: "I handled noisy detections by filtering repeated observations and only acting when the target was stable.",
            keyPoints: ["Filtering", "Repeated observations", "Recovery behaviour"],
            followUpReady: [],
            confidence: 0.9,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .low,
            modelName: "mock",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date()
        )

        try suggestions.saveSuggestionCard(card)

        let rows = try suggestionAlignmentRows(database: database)
        #expect(rows.count == 1)
        #expect(rows[0].detectedQuestionID == question.id)
        #expect(rows[0].joinedQuestionID == question.id)
        #expect(rows[0].suggestionQuestion == question.questionText)
        #expect(rows[0].detectedQuestion == question.questionText)
        #expect(try orphanAutoDetectSuggestionCount(database: database) == 0)
    }

    @Test
    func uiBindingGuardRejectsSuggestionForDifferentQuestion() throws {
        let (appState, _, session) = try makeAppState(client: AlignmentLLMClient())
        let first = try saveQuestion("Could you tell me about yourself?", sessionID: session.id, repository: appState.suggestionRepository, suffix: "self")
        let second = try saveQuestion("Why do you want this role?", sessionID: session.id, repository: appState.suggestionRepository, suffix: "role")
        appState.lastDetectedQuestion = second
        appState.setActiveQuestionForTesting(second)

        let wrongCard = SuggestionCard(
            id: "wrong-card",
            sessionID: session.id,
            questionID: first.id,
            strategy: "Self introduction",
            sayFirst: "I am currently studying MSc Robotics at the University of Manchester.",
            keyPoints: ["MSc Robotics"],
            followUpReady: [],
            confidence: 0.8,
            caution: nil,
            evidenceUsed: [],
            riskLevel: .low,
            modelName: "mock",
            promptVersion: "test",
            rawJSON: nil,
            createdAt: Date(),
            questionText: first.questionText
        )

        let accepted = appState.applySuggestionIfAlignedForTesting(wrongCard, question: second, generationID: nil)

        #expect(accepted == false)
        #expect(appState.currentSuggestion == nil)
        #expect(appState.currentQABinding.bindingStatus == .mismatched)
        #expect(appState.answerQuestionMismatchCount == 1)
        #expect(appState.lastAlignmentError.localizedCaseInsensitiveContains("question"))
    }

    @Test
    func contentRelevanceEvaluatorFlagsAlignedAndMismatchedAnswers() {
        let roleAligned = QuestionAnswerAlignmentEvaluator.evaluate(
            questionText: "Why do you want to join our team?",
            answerText: "I want to join because the role connects robotics, AI, perception, real robot deployment, and engineering growth."
        )
        #expect(roleAligned.verdict == .aligned)

        let roleMismatched = QuestionAnswerAlignmentEvaluator.evaluate(
            questionText: "Why do you want this role?",
            answerText: "The hardest technical challenge was noisy localisation and timing mismatch on the robot."
        )
        #expect(roleMismatched.verdict == .mismatched)

        let candidateQuestionMismatched = QuestionAnswerAlignmentEvaluator.evaluate(
            questionText: "Do you have any questions for us?",
            answerText: "I am currently studying MSc Robotics at the University of Manchester, with a computer science background."
        )
        #expect(candidateQuestionMismatched.verdict == .mismatched)
    }

    private static let longQuestionOnlyTranscript = "Could you tell me a little bit about yourself and what brought you into robotics could you walk me through your LeoRover project what was the hardest technical challenge you faced how did you handle noisy detections or localisation errors why did the diffusion decoder perform better in your MuJoCo evaluation what would you change first if you had another month why do you want to join our team how comfortable are you with Python C plus plus and ROS2 do you have any questions for us"

    private func makeAppState(client: AlignmentLLMClient) throws -> (AppState, AppDatabase, InterviewSession) {
        let database = try TestSupport.makeTemporaryDatabase(prefix: "QuestionAnswerAlignment")
        let settingsRepository = SettingsRepository(database: database)
        try settingsRepository.ensureDefaultProviderConfigurations()
        if let deepSeek = try settingsRepository.providerConfigurations().first(where: { $0.kind == .deepSeek }) {
            try settingsRepository.setActiveRealtimeProvider(id: deepSeek.id)
        }
        let router = LLMRouter(settingsRepository: settingsRepository, clients: [.deepSeek: client])
        let appState = AppState(
            database: database,
            llmRouter: router,
            contextRetrievalService: AlignmentContextRetrievalService()
        )
        appState.delayProvider = MockDelayProvider()
        appState.generationFullCardWatchdogNanoseconds = 2_000_000_000
        let session = try appState.sessionRepository.createSession(mode: .microphone)
        appState.currentSession = session
        return (appState, database, session)
    }

    private func saveQuestion(
        _ text: String,
        sessionID: String,
        repository: SuggestionRepository,
        suffix: String
    ) throws -> DetectedQuestion {
        let question = DetectedQuestion(
            id: "alignment-\(suffix)-\(UUID().uuidString)",
            sessionID: sessionID,
            transcriptSegmentID: nil,
            questionText: text,
            intent: intent(for: text),
            answerStrategy: strategy(for: text),
            confidence: 0.95,
            reason: "Alignment test",
            shouldTrigger: true,
            questionComplete: true,
            modelName: "alignment-test",
            promptVersion: "test",
            createdAt: Date()
        )
        try repository.saveDetectedQuestion(question)
        return question
    }

    private func intent(for text: String) -> QuestionIntent {
        let lower = text.lowercased()
        if lower.contains("project") || lower.contains("leorover") {
            return .projectDeepDive
        }
        if lower.contains("technical") || lower.contains("detections") || lower.contains("diffusion") || lower.contains("python") {
            return .technical
        }
        if lower.contains("role") || lower.contains("team") || lower.contains("questions for us") {
            return .companyFit
        }
        return .behavioral
    }

    private func strategy(for text: String) -> AnswerStrategy {
        let intent = intent(for: text)
        switch intent {
        case .projectDeepDive:
            return .projectWalkthrough
        case .technical:
            return .technicalExplanation
        case .behavioral:
            return .starStory
        case .companyFit:
            return .directAnswer
        case .coding, .salaryVisa, .smallTalk, .instruction, .unclear:
            return .directAnswer
        }
    }

    private func waitUntil(timeout: TimeInterval, predicate: @escaping @MainActor () -> Bool) async throws {
        let start = Date()
        let effectiveTimeout = max(timeout, 45.0)
        while !predicate() {
            if Date().timeIntervalSince(start) > effectiveTimeout {
                throw NSError(
                    domain: "QuestionAnswerAlignmentTests",
                    code: 1,
                    userInfo: [NSLocalizedDescriptionKey: "Timed out waiting for QA alignment state."]
                )
            }
            try await Task.sleep(nanoseconds: 25_000_000)
        }
    }
}

private struct SuggestionAlignmentSQLRow {
    var detectedQuestionID: String?
    var joinedQuestionID: String?
    var detectedQuestion: String?
    var suggestionQuestion: String?
    var answerPreview: String
}

private func suggestionAlignmentRows(database: AppDatabase) throws -> [SuggestionAlignmentSQLRow] {
    try database.dbQueue.read { db in
        try Row.fetchAll(
            db,
            sql: """
            SELECT
              s.detected_question_id,
              dq.id AS question_id,
              dq.question_text AS detected_question,
              s.question_text AS suggestion_question,
              substr(s.say_first, 1, 220) AS answer_preview
            FROM suggestion_cards s
            LEFT JOIN detected_questions dq
              ON s.detected_question_id = dq.id
            ORDER BY s.created_at ASC
            """
        ).map { row in
            SuggestionAlignmentSQLRow(
                detectedQuestionID: row["detected_question_id"],
                joinedQuestionID: row["question_id"],
                detectedQuestion: row["detected_question"],
                suggestionQuestion: row["suggestion_question"],
                answerPreview: row["answer_preview"]
            )
        }
    }
}

private func orphanAutoDetectSuggestionCount(database: AppDatabase) throws -> Int {
    try database.dbQueue.read { db in
        try Int.fetchOne(
            db,
            sql: """
            SELECT COUNT(*)
            FROM suggestion_cards s
            LEFT JOIN detected_questions dq
              ON s.detected_question_id = dq.id
            WHERE s.trigger_path = 'auto_detect'
              AND dq.id IS NULL
            """
        ) ?? 0
    }
}

private final class AlignmentLLMClient: LLMClientProtocol, @unchecked Sendable {
    let providerKind: LLMProviderKind = .deepSeek
    var stageADelayByQuestionKeyword = [String: UInt64]()
    var stageBDelayByQuestionKeyword = [String: UInt64]()

    func testConnection(configuration: LLMProviderConfiguration) async throws -> LLMConnectionTestResult {
        LLMConnectionTestResult(success: true, message: "Mock OK", latencyMS: 0, models: [])
    }

    func chatCompletion(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) async throws -> LLMChatResult {
        let question = questionText(from: messages)
        if let delay = delay(for: question, in: stageBDelayByQuestionKeyword) {
            try await Task.sleep(nanoseconds: delay)
        }
        let content = jsonAnswer(for: question)
        return LLMChatResult(content: content, modelName: "alignment-mock", providerKind: .deepSeek, providerName: "DeepSeek", baseURL: "", latencyMS: 10, isLocal: false, rawResponse: content)
    }

    func chatCompletionStream(
        configuration: LLMProviderConfiguration,
        messages: [LLMChatMessage],
        responseFormat: LLMResponseFormat?,
        options: LLMRequestOptions
    ) -> AsyncThrowingStream<String, Error> {
        let prompt = messages.map(\.content).joined(separator: "\n")
        let question = questionText(from: messages)
        let isStageB = prompt.contains("Return plain text sections only")
        let delay = delay(for: question, in: isStageB ? stageBDelayByQuestionKeyword : stageADelayByQuestionKeyword) ?? 0
        return AsyncThrowingStream { continuation in
            let task = Task {
                if delay > 0 {
                    try? await Task.sleep(nanoseconds: delay)
                }
                if isStageB {
                    for token in sectionAnswer(for: question) {
                        if Task.isCancelled { break }
                        continuation.yield(token)
                    }
                } else {
                    for token in sayFirst(for: question).split(separator: " ", omittingEmptySubsequences: false) {
                        if Task.isCancelled { break }
                        continuation.yield(String(token) + " ")
                    }
                }
                continuation.finish()
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    func listModels(configuration: LLMProviderConfiguration) async throws -> [LLMModelInfo] {
        []
    }

    private func delay(for question: String, in delays: [String: UInt64]) -> UInt64? {
        delays.first { question.localizedCaseInsensitiveContains($0.key) }?.value
    }

    private func questionText(from messages: [LLMChatMessage]) -> String {
        let prompt = messages.map(\.content).joined(separator: "\n")
        if let range = prompt.range(of: #"CURRENT QUESTION TO ANSWER:\s*\n"([^"]+)""#, options: [.regularExpression, .caseInsensitive]) {
            return String(prompt[range])
                .replacingOccurrences(of: "CURRENT QUESTION TO ANSWER:", with: "", options: .caseInsensitive)
                .replacingOccurrences(of: "\"", with: "")
                .trimmingCharacters(in: .whitespacesAndNewlines)
        }
        if let range = prompt.range(of: #"\[Question\]\s*\n(.+?)(\n\n|\z)"#, options: [.regularExpression, .caseInsensitive]) {
            return String(prompt[range])
                .replacingOccurrences(of: "[Question]", with: "", options: .caseInsensitive)
                .trimmingCharacters(in: .whitespacesAndNewlines)
        }
        if let range = prompt.range(of: #"Detected question:\s*\n(.+?)(\n\n|\z)"#, options: [.regularExpression, .caseInsensitive]) {
            return String(prompt[range])
                .replacingOccurrences(of: "Detected question:", with: "", options: .caseInsensitive)
                .trimmingCharacters(in: .whitespacesAndNewlines)
        }
        return prompt
    }

    private func jsonAnswer(for question: String) -> String {
        let sayFirst = sayFirst(for: question)
        return """
        {
          "strategy": "Aligned answer",
          "say_first": "\(sayFirst)",
          "key_points": ["\(keyPoint(for: question))", "Keep it specific to this question"],
          "follow_up_ready": ["I can add more detail if useful."],
          "confidence": 0.88,
          "caution": "None",
          "evidence_used": [],
          "risk_level": "low"
        }
        """
    }

    private func sectionAnswer(for question: String) -> [String] {
        [
            "STRATEGY:\nAligned answer\n",
            "SAY_FIRST:\n\(sayFirst(for: question))\n",
            "KEY_POINTS:\n",
            "- \(keyPoint(for: question))\n",
            "- Keep it specific to this question\n",
            "FOLLOW_UP_READY:\n",
            "- I can add more detail if useful.\n",
            "CAUTION:\nNone\n"
        ]
    }

    private func sayFirst(for question: String) -> String {
        let lower = question.lowercased()
        if lower.contains("about yourself") || lower.contains("tell me about yourself") {
            return "I am studying MSc Robotics at the University of Manchester, with a computer science background and a focus on perception, manipulation, and AI."
        }
        if lower.contains("hardest technical challenge") {
            return "The hardest technical challenge was integrating modules on the real robot, where noisy perception, localisation instability, and timing mismatch made execution unpredictable."
        }
        if lower.contains("leorover") || lower.contains("walk me through") {
            return "My LeoRover project was an autonomous object retrieval robot using ROS2, YOLOv8, navigation, target localisation, and manipulation."
        }
        if lower.contains("noisy detections") || lower.contains("localisation") || lower.contains("localization") {
            return "I handled noisy detections by filtering repeated observations, using stability thresholds, and adding recovery behaviour such as retrying or repositioning."
        }
        if lower.contains("diffusion") {
            return "The diffusion decoder performed better because it produced smoother actions for continuous action distributions and was more robust, reaching seven out of ten successful grasps."
        }
        if lower.contains("another month") || lower.contains("change first") {
            return "I would improve the evaluation pipeline first, testing more objects, initial positions, failure cases, perception robustness, visual grounding, and grasp reranking."
        }
        if lower.contains("join our team") || lower.contains("want this role") || lower.contains("want to join") {
            return "I want this role because it connects robotics, AI, perception, real robot deployment, engineering growth, and deployed systems."
        }
        if lower.contains("python") || lower.contains("ros2") || lower.contains("c++") {
            return "I am comfortable with Python and ROS2 from robotics projects, and I am improving C++ for performance-critical robotics systems."
        }
        if lower.contains("questions for us") || lower.contains("questions for you") {
            return "I would ask how the team evaluates robotics project success when moving from prototypes to reliable real-world deployment."
        }
        return "I would answer this question directly and keep the response specific to the interviewer prompt."
    }

    private func keyPoint(for question: String) -> String {
        String(sayFirst(for: question).prefix(80))
    }
}

private final class AlignmentContextRetrievalService: ContextRetrievalService {
    func retrieveContextWithTrace(
        question: String,
        intent: QuestionIntent,
        maxCVWords: Int,
        maxJDWords: Int,
        strategy: AnswerStrategy?
    ) async throws -> (context: RetrievedContext, trace: RetrievalTrace) {
        let context = RetrievedContext(cvChunks: [], jobDescriptionChunks: [])
        let trace = RetrievalTrace(
            id: UUID(),
            query: question,
            intent: intent.rawValue,
            createdAt: Date(),
            rankedCVChunks: [],
            rankedJDChunks: [],
            includedCVChunks: [],
            includedJDChunks: [],
            excludedCVChunks: [],
            excludedJDChunks: [],
            cvWordsUsed: 0,
            jdWordsUsed: 0,
            cvWordBudget: maxCVWords,
            jdWordBudget: maxJDWords,
            retrievalLatencyMS: 0,
            emptyQueryFallbackUsed: false,
            zeroScoreFallbackUsed: false
        )
        return (context, trace)
    }
}
